mozilla/web-ext

- src/main.js
- webpack.config.js
I guess webpack doesn't let you import modules from an entry point so we need something minimal like this.
> Make an isolated entry point

- src/build.js
- src/cli.js
- src/program.js
- tests/build/adapter.js
- tests/build/test.build.js
Fixes https://github.com/mozilla/web-ext/issues/39
Example of an error you get when you use an unknown option:
````
src/build.js:11
11: export default function build({sourceDir, buildDir}: ProgramOptions) {
^^^^^^^^ property `buildDir`. Property not found in
11: export default function build({sourceDir, buildDir}: ProgramOptions) {
^^^^^^^^^^^^^^ ProgramOptions
````
This protects all command handlers so that they don't use an unknown option and thus they can be unit tested directly without relying on the construction of a complete program object.
It does not protect against defining a new option on a yargs object and *forgetting* to annotate it in ProgramOptions. I can't figure out how to solve that. Even without that protection, the benefit of using one annotation object, ProgramOptions, …
> Protect handlers from using incorrect options

- .npmrc
This will default all npm deps to be added without `^`.
> Add save-prefix setting via .npmrc

- README.md
Fixes https://github.com/mozilla/web-ext/issues/115
Mitigates https://github.com/mozilla/web-ext/issues/117 (since I think that is an npm bug)
> Document installation from source better

- README.md
- package.json
It's easier to type :sparkles:
> chore: changed `npm run develop` to `npm start`

- package.json
- src/cmd/build.js
- tests/fixtures/minimal-web-ext/background-script.js
- tests/fixtures/minimal-web-ext/manifest.json
- tests/helpers.js
- tests/test-cmd/test.build.js
Fixes https://github.com/mozilla/web-ext/issues/85
> Ignore commonly unwanted files when building XPI

- .eslintrc
- CONTRIBUTING.md
- package.json
- src/cmd/build.js
- src/cmd/run.js
- src/cmd/sign.js
- src/firefox/index.js
- src/program.js
- src/util/artifacts.js
- src/util/logger.js
- src/util/manifest.js
- src/util/temp-dir.js
- tests/coverage-reporter.js
- tests/fixtures/minimal-web-ext/background-script.js
- tests/helpers.js
- tests/test-cmd/test.sign.js
- tests/test-firefox/test.firefox.js
- tests/test-util/test.logger.js
- tests/test.program.js
- tests/test.setup.js
* Adds a logger, implements `--verbose`, and converts all old console calls (fixes https://github.com/mozilla/web-ext/issues/33)
* Adds log capturing for tests so that only failing tests spew logs (fixes https://github.com/mozilla/web-ext/issues/120)
Example:
````
$ web-ext build
Building web extension from /Users/kumar/dev/bookmarker-ext/moz-webext
Your web extension is ready: /Users/kumar/dev/bookmarker-ext/moz-webext/web-ext-artifacts/getting_started_example-1.2.25.xpi
````
````
$ web-ext --verbose build
[cmd/build.js][info] Building web extension from /Users/kumar/dev/bookmarker-ext/moz-webext
[util/manifest.js][debug] Validating manifest at /Users/kumar/dev/bookmarker-ext/moz-webext/manifest.json
[cmd/build.js][debug] Not including file …
```
> Adds a logger and implements --verbose

- tasks/mochaTest.js
There are several tests that require I/O and sometimes
these time out when TravisCI is overloaded.
> fix(): Increased test timeout for Travis

- package.json
The webpack banner adds a source-map-support import at the top of the distributed file so it needs to be an explicit dependency.
> fix(): Fixed source-map-support import error

- src/program.js
Fixes #199 
From what I could figure out the build operation accepts no extra options as of now hence the empty object as the argument.
This is my first code contribution here. Let me know if any changes are required for this, thanks!
> fix: Fixed `web-ext --help build`

- package.json
- src/cmd/build.js
- src/program.js
- src/watcher.js
- tests/test-cmd/test.build.js
- tests/test.watcher.js
Fixes https://github.com/mozilla/web-ext/issues/193
This lets you watch files and rebuild the extension, like:
web-ext build --as-needed
It's not such an interesting feature itself but it is a stepping stone to re-installing an XPI which will be one way to reload changes in Firefox.
> Added build --as-needed to watch and rebuild

- src/cmd/run.js
- src/firefox/index.js
- src/firefox/preferences.js
- src/program.js
- src/watcher.js
- tests/test-cmd/test.run.js
- tests/test-firefox/test.firefox.js
- tests/test.watcher.js
Fixes https://github.com/mozilla/web-ext/issues/222
With this patch you can execute `web-ext run` and it will reload your extension in Firefox as you edit the source. If you want to disable it, you can do `web-ext run --no-reload`.
I'm sure that are still corner cases that will need addressing (I've filed [some bugs](https://github.com/mozilla/web-ext/labels/auto-reloading)) but this is probably OK for a first pass. Also, this has a build and reinstall step which can be optimized away later.
Some of the architecture in the `run.js` module feels awkward to me. Let me know if you have some ideas for how to simplify it.
> Run cmd watches source, reloads addon in Firefox

- src/cmd/run.js
- src/firefox/index.js
- src/firefox/remote.js
- src/watcher.js
- tests/helpers.js
- tests/test-cmd/test.run.js
- tests/test-firefox/test.firefox.js
- tests/test-firefox/test.remote.js
Fixes https://github.com/mozilla/web-ext/issues/93
There has been a long platform battle to stabilize the reload add-on function. To keep it simple, https://bugzilla.mozilla.org/show_bug.cgi?id=1269889 introduced a new requirement that the add-on must be installed temporarily before it can be reloaded. This patch uses the remote actor to install the add-on temporarily. 
It's a bit brutal in that it fails hard if the Firefox is too old to allow temporary installation like this (it landed in 49). I think this approach is probably ok for now -- it's a lot easier to test and maintain!
> feat: Run now installs as temporary add-on

- src/cmd/build.js
- src/cmd/run.js
- src/errors.js
- src/firefox/index.js
- src/firefox/remote.js
- src/program.js
- tests/test-cmd/test.run.js
- tests/test-firefox/test.firefox.js
- tests/test-firefox/test.remote.js
Fixes https://github.com/mozilla/web-ext/issues/286
With this patch, here is an example of running in Firefox 48:
````
$ web-ext run
Running web extension from /Users/kumar/dev/bookmarker-ext/moz-webext
Running Firefox with profile at /var/folders/h7/rttdqkks7fl_txp9_rr4j4840000gn/T/67d00895-ed01-41fe-9a04-05b775c1d97c
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Connected to the Firefox remote debugger
run: WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
at /Users/kumar/dev/web-ext/dist/webpack:/src/cmd/run.js:160:13
at /Users/kumar/dev/web-ext/dist/webpack:/src/errors.js:52:14
at process._tickCallback (node.js:368:9)
````
At which point, …
> fix: Re-enabled support for running extensions in Firefox 48

- src/program.js
It's pretty annoying that you only get a stack trace when simply running `web-ext` without any arguments for the first time, so I added help messages.
> Show usage on missing or wrong command.

- .eslintrc
- Gruntfile.js
- src/firefox/remote.js
- src/program.js
- tests/test.program.js
Fixes https://github.com/mozilla/web-ext/issues/169
I also noticed a test was indented wrong -- we didn't have an eslint indent rule. This adds an indent rule (sorry for the noise).
> fix: Missing command/option errors are reported better

- CONTRIBUTING.md
- Gruntfile.js
This is a helper script to generate a changelog from actual commits. It won't be perfect and will likely require some editing but it should make releases easier. Example of a changelog I just generated:
New features:
* Started ignoring node_modules folders by default ([5eff6d5](https://github.com/mozilla/web-ext/commit/5eff6d5))
* Run now installs as temporary add-on ([79c6bf5](https://github.com/mozilla/web-ext/commit/79c6bf5))
* output version when run in verbose mode ([e4280dd](https://github.com/mozilla/web-ext/commit/e4280dd))
* run watches source, reloads addon in Firefox ([61c5087](https://github.com/mozilla/web-ext/commit/61c5087))
* Added --timeout option for signing ([2c176b2](https://github.com/mozilla/web-ext/commit/2c176b2))
* Added remote Firefox reloading support …
> chore: Added a changelog script

- src/cmd/run.js
- tests/test-cmd/test.run.js
Fixes https://github.com/mozilla/web-ext/issues/321
> feat: `web-ext run --pre-install` no longer connects to the remote debugger

- src/cmd/run.js
- src/firefox/remote.js
Fixes https://github.com/mozilla/web-ext/issues/322
> fix: `web-ext run`: increased debugger connection timeout

- README.md
- package.json
Fixes https://github.com/mozilla/web-ext/issues/330
> fix: Installation will now fail if your npm is not up to date

- .eslintrc
- src/cmd/build.js
- src/cmd/run.js
- src/cmd/sign.js
- src/firefox/index.js
- src/firefox/remote.js
- src/util/manifest.js
- tests/test-cmd/test.build.js
- tests/test-cmd/test.run.js
- tests/test-cmd/test.sign.js
- tests/test-firefox/test.firefox.js
- tests/test-firefox/test.remote.js
- tests/test-util/test.manifest.js
Fixes https://github.com/mozilla/web-ext/issues/132, fixes https://github.com/mozilla/web-ext/issues/177
Changes:
* `build`, `run`, and auto-reloading work for manifests without an ID
* `run --pre-install` will error if the manifest doesn't have an ID
* `sign` will error if the manifest doesn't have an ID but this is just temporary until https://github.com/mozilla/web-ext/issues/178 is fixed
> handle extensions without IDs in build/run

- src/program.js
- tests/test.program.js
Fixes https://github.com/mozilla/web-ext/issues/332
> fix: Relative `--source-dir` paths are handled correctly now

- package.json
- src/cmd/sign.js
- src/program.js
- tests/test-cmd/test.sign.js
Supports https://github.com/mozilla/web-ext/issues/178
This feature also requires the patch from https://github.com/mozilla/sign-addon/pull/114
> feat: `web-ext sign` now supports extensions without explicit IDs

- src/program.js
See https://github.com/mozilla/web-ext/pull/340#issuecomment-230045312
> fix: Fixed incorrect help message for `web-ext sign --id`

- .npmignore
- .travis.yml
Fixes https://github.com/mozilla/web-ext/issues/305
This was due to `.gitignore` rules that were being added to `.npmignore` and has been broken (but inconsistently broken) since the 1.0 release. See https://github.com/mozilla/web-ext/commit/2f5c4444#diff-a084b794bc0759e7a6b77810e01874f2R10
Info on how npm uses `.gitignore` in place of a missing `.npmignore` file: https://github.com/npm/npm/wiki/Files-and-Ignores#details-1
> fix: Fixed `Cannot find module '../dist/web-ext'` after installation

- package.json
- src/cmd/index.js
- src/cmd/lint.js
- src/program.js
- src/util/es6-modules.js
- tests/test-cmd/test.lint.js
Fixes https://github.com/mozilla/web-ext/issues/204
> feat: Added `lint` command to validate extension source

- .eslintrc
- package.json
Use ./node_modules/.bin/grunt directly instead of inline Node scripts in package.json
> Use ./node_modules/.bin/grunt directly instead of inline Node scripts in package.json

- src/firefox/preferences.js
This is a port of https://github.com/mozilla-jetpack/jpm/pull/561 and fixes #406.
> fix: Hide reader mode UI tour and Normandy CDN errors

- src/cmd/lint.js
- tests/test-cmd/test.lint.js
Fixes https://github.com/mozilla/web-ext/issues/397
Tasks:
> fix: `web-ext lint`: ignore node_modules and other artifacts

- .eslintrc
- .flowconfig
- package.json
- src/cmd/build.js
- src/cmd/lint.js
- src/cmd/run.js
- src/cmd/sign.js
- src/firefox/index.js
- src/firefox/preferences.js
- src/firefox/remote.js
- src/program.js
- src/util/logger.js
- src/util/manifest.js
- src/util/temp-dir.js
- src/watcher.js
- tests/helpers.js
- tests/test-cmd/test.lint.js
- tests/test-cmd/test.run.js
- tests/test-firefox/test.preferences.js
- tests/test-firefox/test.remote.js
- tests/test-util/test.logger.js
In this PR there are the changes related to the additional flow type checking (that are currently part of #411) extracted and extended with much more flow types checks.
Once we complete this PR, #411 will be rebased on the final version of these changes and it will be limited to the introduction of the `async/await` syntax (with the additional safety net provided by the additional static analysis that flow will be able to provide).
> Test: add more flow types

- Gruntfile.js
- package.json
- tasks/watch.js
Fixes #339 
The `.cache` directory is no longer created while running `npm run lint`
> fix: disabled caching during npm run lint

- src/cmd/run.js
- src/program.js
- tests/test-cmd/test.run.js
Fixes #116 
For some reason, changing `firefox` to `firefoxApp` even on just [this](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L167) line makes the tests fail.
> fix: --firefox-binary to --firefox

- src/program.js
Removed the hack which was in place to do this & replaced it with the `coerce` function to resolve the path of the source directory. Solves #438
> refactor: use coerce function of yargs to resolve path

- src/cmd/run.js
- src/firefox/index.js
- tests/test-cmd/test.run.js
This PR fixes an issue with the optional Firefox binary path option and contains some tweaks to the related declared flow types, which shows how we can force flow to raise errors on this kind of issues (missing optional parameters in the `parameters` and `options` objects)
> fix: firefox binary path not passed in the run method exported by 'src/firefox/index'

- src/program.js
- tests/test.program.js
Fixes #398 
Also added a test for checking if an argument is passed to a sub-command.
> fix: show an error if an argument is passed to the lint command

- tests/test.program.js
> fix: test case checking for unknown sub-command options doesn't work

- src/errors.js
- tests/unit/test.errors.js
Fixes https://github.com/mozilla/web-ext/issues/220
> fix: Added errno for errors with specific codes

- tasks/watch.js
Originally I thought Flow errors would get in the way and that tests should be your first point of feedback. I now think Flow errors are more helpful as early feedback. However, I still think lint errors should continue to come after test suite errors because those tend to be less crucial (like style nits).
> chore: Run Flow checks before running tests

- CONTRIBUTING.md
- package.json
Fixes #551
Added the [git-hooks-win](https://www.npmjs.com/package/git-hooks-win) package to package.json under developer dependencies. This package has zero dependencies and supports the current model of format verification prompt that is available to Mac OS users for Windows users as well. 
This was the error message I got before adding the package
And after installing the package, prompt works correctly
Tested on Windows 10.
> fix: Fixed commit format verification prompt for Windows users

- src/cmd/run.js
I realized that it may not be clear to developers that their extension will be reloaded in the background
> feat: `web-ext run` now makes it clear when auto-reloading is turned on

- src/cmd/run.js
- src/watcher.js
I think this looks a little nicer:
````
$ web-ext run
Running web extension from /Users/kumar/dev/webextensions-examples/borderify
Running Firefox with profile at /var/folders/h7/rttdqkks7fl_txp9_rr4j4840000gn/T/92fcc202-9d94-4007-8408-e266a4038d1b
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed /Users/kumar/dev/webextensions-examples/borderify as a temporary add-on
The extension will reload if any source file changes
14:27:38 GMT-0500 (CDT): Reloaded extension: borderify@mozilla.org
14:27:48 GMT-0500 (CDT): Reloaded extension: borderify@mozilla.org
14:27:53 GMT-0500 (CDT): Reloaded extension: borderify@mozilla.org
````
> fix: The `web-ext run` command is a little less chatty now

- src/cmd/sign.js
- tests/unit/test-cmd/test.sign.js
Fixes #585 
- throw a `UsageError` when the sign command fails to sign an add on
- modified the current test which makes the test fail to check for the error
- verified the output of `$ echo $?`, it prints 1
@kumar303, will this work? I don't think we need a wrapper or am I missing something?
> Sign command exits with zero status when signing fails

- src/cmd/build.js
- src/cmd/sign.js
Fix #181 
Manually tested with example addon
> fix: Don't log info about the built extension when signing

- .eslintrc
- src/cmd/build.js
- src/cmd/run.js
- src/errors.js
- src/firefox/preferences.js
- src/program.js
- tests/unit/helpers.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-util/test.artifacts.js
- tests/unit/test-util/test.logger.js
- tests/unit/test-util/test.manifest.js
- tests/unit/test.watcher.js
I added a few rules after I had to be an annoying reviewer on [this patch](https://github.com/mozilla/web-ext/pull/577) :) 
* Added [brace-style](http://eslint.org/docs/rules/brace-style) to catch some if/else consistency problems I've been seeing lately (I actually haven't been nagging about these in reviews)
* Added deeper [indent](http://eslint.org/docs/rules/indent) rules. These are nits that I've commented about on reviews.
* Added [object-property-newline](http://eslint.org/docs/rules/object-property-newline). This is an attempt to address inconsistent new lines in property lists but doesn't fully address it.
> chore: improve linting rules for brace styles

- tests/unit/test-firefox/test.remote.js
Some PR builds on Node 4 were getting:
````
/home/travis/build/mozilla/web-ext/tests/unit/test-firefox/test.remote.js
274:30  error  Expected indentation of 12 spaces but found 29  indent
````
> chore: fix mysterious lint error

- package.json
- src/cmd/lint.js
- src/program.js
- tests/unit/test-cmd/test.lint.js
This patch adds support for using `--warnings-as-errors` as a parameter for the lint command.
This enables the functionality provided in the PR https://github.com/mozilla/addons-linter/pull/1016 and partially resolves the issue https://github.com/mozilla/addons-linter/issues/1014.
Once `addons-linter` has PR accepted and merged, [packages.json](https://github.com/mozilla/web-ext/blob/master/package.json#L47) will also need to have the package-version bumped to fully resolve and close the issue.
> Support warnings-as-errors

- package.json
- src/cmd/build.js
- src/util/manifest.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-util/test.manifest.js
Fixes #491 
Used the [json-parse](https://github.com/sindresorhus/parse-json) to display line column number for providing context for syntax errors in JSON files.
> fix: Format JSON parse errors so that they provide file context

- src/cmd/run.js
- src/firefox/index.js
- src/firefox/preferences.js
- src/program.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-firefox/test.preferences.js
- tests/unit/test.program.js
Current commit without repeated option and with preferences assignment commented. Since there are so many changes for this one, I'd like to know if it is the correct approach so far.
Fixes https://github.com/mozilla/web-ext/issues/88
> feat: install and run an extension with custom Firefox preferences  

- .eslintrc
- tests/functional/test.cli.run.js
- tests/unit/test-firefox/test.firefox.js
- webpack.config.js
> fix: added eslint rule for shorthand property assignment

- .eslintrc
- src/cmd/build.js
- src/cmd/run.js
- src/cmd/sign.js
- src/firefox/index.js
- src/firefox/preferences.js
- src/firefox/remote.js
- src/program.js
- src/util/logger.js
- src/util/manifest.js
- src/util/temp-dir.js
- tests/functional/test.cli.lint.js
- tests/unit/helpers.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-firefox/test.preferences.js
- tests/unit/test-util/test.artifacts.js
- tests/unit/test-util/test.is-directory.js
- tests/unit/test-util/test.logger.js
- tests/unit/test-util/test.manifest.js
- tests/unit/test-util/test.temp-dir.js
- tests/unit/test.program.js
> fix: Added prefer-const to eslint and related changes

- src/firefox/preferences.js
- tests/unit/test-firefox/test.preferences.js
This PR contains two small fixes which cover the following corner cases:
- custom prefs values which contains '=' chars
- custom prefs which do not specify a value
> fix: Support custom prefs values that contains '=' chars

- src/program.js
- tests/unit/test.program.js
`demand()` changed after yargs 6.6.0 https://github.com/yargs/yargs/pull/740
Test bustage was in https://travis-ci.org/mozilla/web-ext/builds/189002823 (but this mysteriously didn't fail in the PR that actually upgraded yargs, hmm)
> chore: after upgrading yargs, fix deprecated use of demand()

- package.json
- src/cmd/run.js
- src/util/desktop-notifier.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-util/test.desktop-notifier.js
I've installed a package which seemed well thought-through and maintained. However, I am not sure about how effective catching the error is currently. 
fixes #511
> feat: show desktop notifications on addon reload

- CONTRIBUTING.md
Added information on adding new cli options and some general CLI info to Contributing Guide.
> docs: adding new cli option

- CONTRIBUTING.md
This PR adds some "flowtype" docs to the CONTRIBUTING.md file (as part of #739).
Add more info in the intro to flow:
include some helpful example:
> docs: Added more docs related to the flow errors

- .editorconfig
- package.json
- src/cmd/build.js
- src/firefox/index.js
- src/util/stream-to-promise.js
- tests/functional/common.js
- tests/functional/fake-amo-server.js
- tests/functional/fake-firefox-binary.bat
- tests/functional/test.cli.build.js
- tests/functional/test.cli.lint.js
- tests/functional/test.cli.nocommand.js
- tests/functional/test.cli.run.js
- tests/functional/test.cli.sign.js
- tests/unit/helpers.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-util/test.manifest.js
- tests/unit/test.watcher.js
This PR makes `npm test` be able to pass under Windows 7, Node 7.0.0. However `functional/test.cli.run.js` still failed since web-ext uses `fx-runner` to spawn the browser, which is a fake .js file. Any idea how to fix this?
The original `stream-to-promise` doesn't ensure that the file descriptor is closed. This sometimes makes `fs.rmdir` throws during cleaning the tempdir when testing.
A small test script:
```javascript
var streamToPromise = require("stream-to-promise"),
fs = require("fs");
function streamToPromise2(stream) {
return new Promise(resolve => {
stream.on("close", resolve);
});
}
function test(toPromise, fn) {
return new Promise(resolve => {
var i = 0;
(function loop() {
var stream = fs.createWriteStream(fn),
pending = toPromise(stream);
stream.end("test");
pending.then(() => …
```
> test: Windows compatibilities

- tasks/travis-pr-title-lint.js
Fixes #767
This PR introduces a small change in the `travis-pr-title-lint` grunt task that fixes the `conventional-changelog-lint` config loading.
Based on the failure from this Travis build https://travis-ci.org/mozilla/web-ext/jobs/193576176, we noticed that the configuration file `'.conventional-changelog-lintrc'` was not loading correctly, by looking at the `conventional-changelog-lint`, sources it looks like the reason was related to the usage of `getConfiguration` with the wrong parameters (which unfortunately doesn't generate any complains or promise rejection, it just return a default configuration based on the selected preset).
> fix: Fixed loading changelog lint config

- src/util/file-filter.js
- src/watcher.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-util/test.file-filter.js
- tests/unit/test.watcher.js
Fixes #789
I tried to drop "relative mode" to make FileFilter simpler:
1. `sourceDir` defaults to `.`
2. `FileFilter` would only match files inside `sourceDir`. (prefix all patterns with `sourceDir`)
3. `sourceDir` and `artifactsDir` are resolved with `cwd`.
4. `wantFile(path)` is resolved with `cwd`.
The change in (2) makes `proxyFileChanges` unable to filter out `baseIgnoredPatterns` since it doesn't know `sourceDir`, and I just removed that test.
> fix: Ignore artifactsDir only if it is a sub directory of sourceDir

- src/cmd/run.js
Saw the typo prominently featured in the first screenshot of this blog post: https://blog.mozilla.org/addons/2017/02/09/web-ext-1-8-released/
> style: Fix typo: “occured” → “occurred”

- src/firefox/index.js
Fixes #820
I think the only fix for this was to convert this [line of code](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L133) from `log.info(...)` to `log.debug(...)`. You don't see the temporary path when you type `web-ext run`, but you do when you run `web-ext --verbose run`.
> feat: Removed temporary profile path from `web-ext run` logging

- src/cmd/sign.js
- tests/unit/test-cmd/test.sign.js
This is meant to fix #843.
Also worth noting, some unrelated tests failed on my computer, due to i18n : 
```
1) program.Program throws an error about unknown options:
AssertionError: expected 'Argument inconnu: nope' to match /Unknown argument: nope/
at Function.assert.match (node_modules/chai/lib/chai/interface/assert.js:883:32)
at dist/webpack:/tests/unit/test.program.js:226:16
at runMicrotasksCallback (internal/process/next_tick.js:58:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2) program.Program throws an error about unknown sub-command options:
AssertionError: expected 'Argument inconnu: nope' to match /Unknown argument: nope/
at Function.assert.match …
```
> fix: Allowed --ignore-files option within sign command

- src/cmd/run.js
- src/firefox/index.js
- src/firefox/remote.js
- tests/unit/test-cmd/test.run.js
> fix: initiate remote debugger with firefox runner's port

- README.md
I've seen this issue come up a number of times where people miss the installation step of `web-ext` https://github.com/facebook/react-devtools/issues/847
Also when installed as one of the `devDependencies` then services like greenkeeper will keep the packaged updated where as global installations tend to never be updated by developers and so new versions can be missed and teams get out of sync.
In general I avoid the global install approach but I added it as an option here.
> docs: Add instructions for a devDependencies install

- src/firefox/index.js
- tests/unit/test-firefox/test.firefox.js
This PR extracts (and expands) the "checks for the Firefox default profile" pieces that we are working on in #968 to fix #1005
> fix: Prevent --keep-profile-changes on default Firefox profiles

- bin/web-ext
- src/cmd/build.js
- src/cmd/docs.js
- src/cmd/index.js
- src/cmd/lint.js
- src/cmd/run.js
- src/cmd/sign.js
- src/extension-runners/index.js
- src/main.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.extension-runners.js
- tests/unit/test.web-ext.js
Fixes https://github.com/mozilla/web-ext/issues/683
This only supports minimal programmatic use. You can just execute raw functions without any argument validation, like:
```js
import webExt from 'web-ext';
webExt.cmd.run({shouldExitProgram: false, firefox: '...', sourceDir: '...'})
.then((extensionRunner) => {
console.log(extensionRunner);
});
```
One would have to set up verbose logging manually:
```js
webExt.util.logger.consoleStream.makeVerbose();
webExt.cmd.run({shouldExitProgram: false, firefox: '...', sourceDir: '...'});
```
You can also disable the use of standard input:
```js
webExt.cmd.run({shouldExitProgram: false, noInput: true});
```
> feat: You can now use web-ext programatically, e.g. `webExt.cmd.run()`

- .eslintrc
- package.json
Closes #992 
This upgrades the linter but also adjusts some eslint rules. For some mysterious reason, the linter triggered eslint errors.
> chore: Upgrade linter and adjust eslint rules

- src/cmd/run.js
- src/program.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test.program.js
I was trying to track down the `--pref` option and I became confused until I realized it was getting aliased in `program.js`. I don't think this is the right place to alias it because it's not an obvious place to look. Also, it introduces an inconsistency since no other option is aliased like that. Most importantly, I'd like to keep the mapping of option names to top-level callback arguments one-to-one, whenever possible, for sanity.
> chore: clean up aliasing of --pref

- README.md
- src/program.js
The command descriptions now follow the new extension terminology: https://wiki.mozilla.org/Add-ons/Terminology
> docs: Add summary to docs and fix command descriptions

- .travis.yml
- Gruntfile.js
- appveyor.yml
- package.json
- tasks/configs/copy.js
- tests/functional/common.js
Closes #1076
Here's an explanation of the problem. Eslint needs to load the `eslint-recommended` plugin. Before the latest `addons-linter` upgrade, it worked like this:
```
$ eslint --debug 'src/**/*.js'
...
eslint:config-file Loading /Users/kumar/dev/web-ext/node_modules/eslint/conf/eslint-recommended.js +7ms
```
This works fine because there's only one `eslint` in the tree:
```
$ yarn list eslint
yarn list v1.1.0
└─ eslint@3.19.0
```
After upgrading `addons-linter`, we introduce a new `eslint` and it loads a different version of `eslint-recommended`:
```
$ eslint --debug 'src/**/*.js'
...
eslint:config-file Loading /Users/kumar/dev/web-ext/node_modules/addons-linter/node_modules/eslint/conf/eslint-recommended.js +4ms
```
Here's where you can see the conflicting packages:
```
$ yarn list …
```
> fix(package): update addons-linter to version 0.26.1

- .travis.yml
- appveyor.yml
- package.json
> fix(package): update addons-linter to version 0.30.0 and ensure that CI tests fail on production npm binary components in dependencies

- package.json
This PR update the addons-linter dependency to the 0.31.0, which include the upstream fix for #1164
> chore(package): update addons-linter to version 0.31.0

- src/config.js
- src/program.js
- src/util/file-exists.js
- tests/unit/helpers.js
- tests/unit/test-util/test.artifacts.js
- tests/unit/test-util/test.file-exists.js
- tests/unit/test.config.js
- tests/unit/test.program.js
Fixes https://github.com/mozilla/web-ext/issues/730
> feat: Discover config files in home dir, working dir

- package.json
This PR updates the addons-linter dependency to the version 0.32.0 (which fixes #1134)
> chore(package): update addons-linter to version 0.32.0

- src/extension-runners/firefox-android.js
- tests/unit/test-extension-runners/test.firefox-android.js
Fixes a minor typo in the `--firefox-apk` error message
> fix: Fix typo in --firefox-apk error message

- src/config.js
- tests/unit/test.config.js
This PR contains the changes (and additional test case) to fix #1198
> fix: Config file array files should be recognized as options of array type

- package.json
- tests/unit/helpers.js
> chore(package): update flow-bin to version 0.63.1

- src/extension-runners/firefox-android.js
I think this can be a hidden debug message. What do you think?
> fix: Change Android cleanup message on exit

- src/extension-runners/firefox-android.js
- tests/unit/test-extension-runners/test.firefox-android.js
This pull request contains the changes needed to fix #1211 
The android "external storage permissions" are optional only starting from Marshmallow (android-23), and so they cannot be "granted" on the previous android versions.
This patch also fixes a bug in the test suite (and in the code), the previous version of the test was wrongly returning undefined from the `getAndroidVersionNumber` spy and so the test wasn't really testing the behavior on the expected android version number (and the implementation wasn't raising an error for an unexpected "not number" android version).
> fix: Granted android permissions are only needed for android >= 23

- src/firefox/preferences.js
- tests/unit/test-firefox/test.preferences.js
This PR contains a very small change, needed to fix #1114
> fix: Prevent the privacy policy info page to be opened on every run

- src/cmd/run.js
- src/config.js
- src/firefox/preferences.js
- src/program.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-firefox/test.preferences.js
- tests/unit/test.config.js
- tests/unit/test.program.js
This PR contains a set of proposed changes to fix #1213, #1214 and #1215 
#1213 is fixed by prevent `applyConfigToArgv` to recurse on an array of config values (by consider it as a sub-command config section by mistake)
#1214 is fixed by checking if `adjustedArgv.verbose` is `true` after we loaded and applied the config file and then calling `logStream.makeVerbose` accordingly.
#1215 proposed fix is (as describe in [this comment](https://github.com/mozilla/web-ext/issues/1215#issuecomment-359062606)) to mark explicitly as array the options that may makes sense as an array of values in the config file
> fix: Do not treat an array of config values as a sub-command config section

- package.json
Closes #1248 
This patch release was a precaution against a previously released malicious version https://github.com/conventional-changelog/conventional-changelog/issues/282#issuecomment-365367804
> chore(package): update conventional-changelog-cli to version 1.3.13

- src/config.js
- tests/unit/test.config.js
Fixes #1166
This time I modified the `loadJSConfigFile()` function to parse package.json, and I also added test coverage for it.
> feat: added package.json as an option for configs

- tests/unit/test-extension-runners/test.extension-runners.js
Actually MultiExtensionRunnerParams does not have such parameters at all.
> chore: Drop unused getFakeFirefox and getFakeRemoteFirefox

- package.json
- src/extension-runners/index.js
- src/util/temp-dir.js
This pull request supersedes #1259 by updating flow-bin to version 0.68.0 and contextually fixing a new flow check error that the previous flow version wasn't yet able to catch (basically flow 0.68.0 is figuring out the `stdin.isTTY` is going to be available only if we already checked that it is an instance of `tty.ReadStream`, which is actually true and so reversing the order of those checks fixes the flow error).
Thanks to @hiikezoe for fixing in #1292 and #1293 the other two issues that were making the flow-check step to fail with flow-bin 0.68.0 (flow is definitely becoming smarter and it is able to catch more type issues at every new version, and it is definitely worth to update it sooner than later).
(there is also a small change, in a separate commit, applied to …
> chore(package): update flow-bin to version 0.68.0 and fixed new related errors

- package.json
This pull request updated the addons-linter dependency to the last released version 0.41.0
(and it supersedes #1252).
> fix(package): update addons-linter to version 0.41.0

- src/cmd/build.js
This pull request applies a super small change to fix an incompatibility with json-parse-better-errors 1.0.2, due to this change (and the fact that we pass a nodejs Buffer instead on a plain string):
- https://github.com/zkat/json-parse-better-errors/compare/v1.0.1...latest#diff-168726dbe96b3ce427e7fedce31bb0bcR9
Not that we have asked for a new version, but its a "relaxed" dependency of one of our dependencies:
- https://github.com/sindresorhus/parse-json/blob/a35850ac2881cba5be3b10cd8ffd5c8567f3cd02/package.json#L36
and so, new installations get json-parse-better-errors 1.0.2 and the different behavior (included any new travis job: https://travis-ci.org/rpl/web-ext/builds/365291384#L2733)
isn't that fun?
> fix(parse-json): Fixed incompatibility with json-parse-better-errors 1.0.2

- src/cmd/docs.js
- src/cmd/index.js
- src/cmd/run.js
- src/extension-runners/firefox-android.js
- src/extension-runners/index.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.extension-runners.js
- tests/unit/test.web-ext.js
Simple commands like `web-ext --help` now require less than a second instead of 4 seconds to complete.
And `web-ext run` also runs slightly over 3 seconds faster (https://github.com/mozilla/web-ext/pull/1302#issuecomment-380786023)
Fixes #1301
> fix: Improve web-ext start-up time by lazy loading some modules

- .travis.yml
- appveyor.yml
- tests/unit/helpers.js
- tests/unit/test-extension-runners/test.extension-runners.js
- tests/unit/test-extension-runners/test.firefox-android.js
- tests/unit/test-util/test.logger.js
This PR contains some additional changes to the test units needed to successfully run all the tests on node >= 8 (and fix the remaining issues from #1129).
In particular it fixes the ` RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined` errors due to the ReadStream/WriteStream instances created in tests (e.g. to mock the stdin stream).
On this fixes we currently need to suppress some flow type errors (due to the nodejs type definitions already defined in flow not yet including this changes between node6 and node8).
Once ReadStream/WriteStream type definitions are updated in flow itself, flow is going to complain that these suppress comments are not suppressing any actual error and we will know that we can remove the suppress comments from there.
> fix(test): Fixed remaining issues for run test successfully on node >= 8

- package.json
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.extension-runners.js
- tests/unit/test-firefox/test.preferences.js
- tests/unit/test.config.js
This pull request update most of the dev dependencies, and introduce some small fixes needed on the test suites while updating some of this dependencies (flow-bin and chai).
This PR supersedes and fixes #1182 #1205 #1216 #1263 #1267 #1280 #1283 #1286 #1291 #1300 #1304 #1305 #1308 #1311 #1315 #1329 #1332
> chore: Updated dev dependencies

- tests/functional/fake-amo-server.js
In our fake AMO server, we are immediately sending a response without consuming the HTTP request body. This code pattern is known to cause EPIPE failures (see https://github.com/nodejs/node/issues/12339). The fix is to consume the request body before responding.
Minimal local reproduction (tested with Node.js v10.6.0):
```sh
path/to/web-ext/tests/functional/fake-amo-server.js
```
```sh
$ node -e 'require("http").request({port:8989,method:"POST"},res=>{console.log(res.statusCode); res.pipe(process.stdout)}).end("x".repeat(1E7))'
200
{"url":"http://localhost:8989/validation-results/"}events.js:167
throw er; // Unhandled 'error' event
^
Error: write EPIPE
at WriteWrap.afterWrite [as oncomplete] (net.js:835:14)
Emitted 'error' event at:
at Socket.socketErrorListener (_http_client.js:382:9)
at …
```
> fix(test): Avoid EPIPE error in "web-ext sign" test

- package.json
This PR updates the addons-linter to version 1.2.6, and so it supersedes and fix #1326.
> fix(package): update addons-linter to version 1.2.6

- src/firefox/preferences.js
The `javascript.options.strict` option results in lots of log spam, which not only makes debugging harder, but also slows down Firefox.
The `javascript.options.showInConsole` option was removed too because true is already the default value.
Fixes #1355
> fix: Use default javascript.options.strict=false

- package.json
This PR updates the addons-linter npm dependency from version 1.2.6 to version 1.3.1 (and supersedes #1353).
The updated addons-linter provides the following additional features/fixes (as mentioned in https://github.com/mozilla/web-ext/pull/1353#issuecomment-411187167):
- Added basic support for WebExtension dictionaries
- WebExtensions API Schemas updated up to Firefox 62b15
- Added support for ES6 modules
> fix(package): update addons-linter to version 1.3.1

- src/cmd/build.js
- src/util/manifest.js
- tests/unit/test-cmd/test.build.js
> fix: Permit single-line JSON comments

- .travis.yml
This PR is a small follow up related to #1385, the travis windows workers are pretty slow (not very surprising to be fair) and it seems that travis is having issues to initialize the node_js 6 environment from time to time (and so in that case the job is marked as errored even if the tests haven't been executed at all).
I think that it would be reasonable to run on windows only the last nodejs version that we are testing web-ext on CI, so that we can speed up the CI job a bit and spare Travis from allocating two windows worker for every CI job.
> chore: Skip node_js 6 on travis windows workers

- .travis.yml
This PR skips some redundant steps from the travis windows workers (basically skipping steps that are not really needed to run on the slower travis window workers, because the exact same step is already executed in the faster travis linux workers and so an issue is likely already been caught by them).
> chore: Skipped nsp-check and travis-pr-title-lint npm scripts on travis windows workers

- src/extension-runners/firefox-android.js
- tests/unit/test-extension-runners/test.firefox-android.js
New versions of firefox-android appear to use abstract unix sockets instead of filesystem sockets
for the debugging connection. This change ensures support for both the original filesystem
namespace and also the abstract namespace.
> fix(firefox-android): Support abstract sockets for RDB

- .travis.yml
- tasks/configs/mochaTest.js
Currently the travis windows worker fails on tagged releases because it tries to deploy on npm, e.g. see:
https://travis-ci.org/mozilla/web-ext/jobs/452842982#L1228
Deploying on npm from the travis window worker is not something that we really want (or care about) and so we should ask travis to skip the deploy task completely on any windows job. 
Based on the [relevant travis docs](https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on) this change should avoid that (unfortunately we will learn if it worked as expected only once we create the next tag).
> fix: Prevent travis windows worker from trying to deploy new tags on npm

- package.json
This PR updates the addons-linter dependency to version 1.4.1, which is also the last addons-linter version that is still compatible with nodejs 6.
Starting from addons-linter 1.4.2, the addons-linter includes mdn-browser-compat-data as an additional npm dependency, and mdn-browser-compat-data uses some js syntaxes that are not supported on nodejs 6.
> feat(addons-linter): Updated addons-linter to version 1.4.1

- package.json
This is going to be the last web-ext version still compatible with nodejs 6 👋.
* Added release channel as optional sign parameter (simple test) ([#1400](https://github.com/mozilla/web-ext/issues/1400)) ([942c308](https://github.com/mozilla/web-ext/commit/942c308))
* Updated `web-ext lint` to use addons-linter to version 1.4.1 ([#1407](https://github.com/mozilla/web-ext/issues/1407)) ([4eb7ca0](https://github.com/mozilla/web-ext/commit/4eb7ca0))
* Added support for `browser_specific_settings` as an alias for the `applications` manifest key (mozilla/addons-linter#2280)
* Added [new linting rules for the validation of static themes](https://mozilla.github.io/addons-linter/#static-theme-%2F-manifest.json) (mozilla/addons-linter#2271, mozilla/addons-linter#2051)
* See all addons-linter …
> chore: bump package version for release 2.9.3

- .nsprc
- package.json
This PR updates the fx-runner npm dependency to version 1.0.10, which fixes failures on travis due to npm audit detecting a security advisory related to the lodash version used in the previous fx-runner version (https://npmjs.com/advisories/782).
I had to still add that advisory to the list of the ones to ignore (by including it into the .nsprc file) because there are still 2 dev dependency that depends on the vulnerable one (I'll deal with that in a follow up, once I can remove or update those dev dependency).
> chore: Updated fx-runner to version 1.0.10

- package-lock.json
- package.json
- src/firefox/index.js
- src/util/artifacts.js
- src/util/promisify.js
- src/util/temp-dir.js
- src/util/zip-dir.js
- tests/functional/common.js
- tests/unit/helpers.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-util/test.manifest.js
- tests/unit/test-util/test.promisify.js
This PR replaces es6-promisify with a small util module included in-tree.
The new es6-promisify release has deprecated the multiArgs option, that is basically the only es6-promisify option that we use, and so given that we only have a small number of places where we were using es6-promisify I opted to replace it with a small module that should provide just "what we actually use" (and in the end "one less npm dependency" is nice side-effect ;-)).
This PR also unvealed some mistakes we made on some of the mocks defined in the unit test suite (same issues were also triggered by upgrading the project to the API of the last es6-promisify release, but I didn't digged too much into why with the previous version of es6-promisify they did seem to work just fine).
> chore: Replaced es6-promisify with nodejs 8 util.promisify helper

- .nsprc
- package-lock.json
- package.json
This PR update the addons-linter to version 1.7.0, which also fix its dependency from a js-yaml version which has a security vulnerability (https://npmjs.com/advisories/788).
The js-yaml security advisory is also being added temporarily to the .nsprc file, because mocha 6.0.2 is also depending from the vulnerable js-yaml version (a fixed mocha version is going to be released as part of the [upcoming mocha 6.1.0 version](https://github.com/mochajs/mocha/commit/586bf78499b23e5f514b534cf93cf31e53fd0a42#r32896240)).
> fix: Updated addons-linter to version 1.7.0

- src/util/adb.js
- tests/unit/test-util/test.adb.js
This PR contains the changes introduced by #1583, to ensure that web-ext will be able to detect the granted permissions on android versions where `pm dump` uses a comma as separator between permission name and "granted=true" (e.g. as in the Samsung Galaxy S5 original ROM), with the addition of a test case to cover the fix in the automated unit tests.
> fix: Allow comma as separator when checking permissions via adb

- src/extension-runners/firefox-android.js
- src/firefox/preferences.js
- tests/unit/test-extension-runners/test.firefox-android.js
This PR has two independent fixes, both of which can be used to fix #1592.
The first patch adds support for `--pref`, so that one could have used `web-ext run --target=firefox-android --android-device=emulator-5554 --pref=browser.link.open_newwindow=3` to work around #1592
The second patch restores the default value of the `browser.link.open_newwindow` preference so that bug #1592 does not occur any more.
I tested both, by launching `web-ext run` for a simple extension:
manifest.json:
```json
{
"name": "Link to website",
"version": "1",
"manifest_version": 2,
"background": {
"scripts": ["background.js"]
}
}
```
```javascript
// background.js
chrome.tabs.create({url: "page.html"});
```
```html
<meta name=viewport content="width=device-width">
<a href="https://example.com/" …
```
> fix: custom preferences on Fennec

- scripts/audit-deps
This PR contains some small changes applied to the `audit-deps` script, to fix #1604 and make it easier to investigate failures related to the `audit-deps` script based on the logs collected by the travis CI job
> chore(audit-deps): Re-run npm audit on ENETUNREACH errors

- src/cmd/build.js
- tests/unit/helpers.js
This PR contains two fixes needed to prevent linting errors on eslint v6 (e.g. See https://travis-ci.org/mozilla/web-ext/jobs/550038386#L227).
Unfortunately these fixes are not yet enough to be able to merge #1635: 
(once these linting errors are fixed) there are test failures related to the "addons-linter not being yet adapted to run successfully on eslint 6" (even if the addons-linter has eslint 5 has its own exact dependency, the presence of eslint 6 as a web-ext dependency doesn't seem to be forcing npm to esplicitly include eslint 5 in the addons-linter node_modules dir as we would expect).
> fix: Fixed linting error related to eslint v6

- .travis.yml
- scripts/lib/config.js
- scripts/test-functional
This PR adds an additional step to the travis CI jobs, to verify that web-ext is able to load the expected npm dependencies if installed with the "npm legacy bundling mode".
Follow up for #1634
> test: Run functional tests in legacy bundling mode as part of the travis CI jobs

- .nsprc
- scripts/audit-deps
This PR adds the recent advisories related to set-value and mixed-deep (which are not direct web-ext dependencies, but still required by watchpak and webpack) to the nsprc ignore list, because it is currently triggering failures in any pull request (because the CI jobs fails on the "Npm audit and lint github pr title" step, [e.g. as in this job](https://travis-ci.org/mozilla/web-ext/jobs/557924886)).
TODO:
> chore: Added last set-value and mixed-deep advisories to the nsprc ignore list

- src/program.js
- tests/unit/test.program.js
The yargs upgrade from 6.6.0 to 13.2.1 in edebef46eb broke the documented ability to pass multiple files to ignore after the `--ignore-files` (aka `-i`) parameter. This is because yargs 11 started to treat `requiresArg` as an implicit `nargs: 1`, i.e. to accept exactly one value only.
There is an open upstream bug about this issue: https://github.com/yargs/yargs/issues/1098
This patch works around the issue by dropping `requiresArg` and validating the number of parameters in the `execute` function instead.
Fixes #1641
> fix: support multiple values after --ignore-files again

- package-lock.json
- package.json
- src/cmd/run.js
- src/extension-runners/chromium.js
- src/extension-runners/firefox-android.js
- src/extension-runners/index.js
- src/program.js
- src/util/manifest.js
- tests/functional/test.cli.run.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.chromium.js
- tests/unit/test-extension-runners/test.firefox-desktop.js
This PR introduces a new `'chromium'` target and a new `--chromium-binary` cli option 
(which covers #809 and part of #1130).
Internally it uses the `chrome-launcher` npm package to manage the chromium instance and so by default it tries to discover and launch the Chrome or Chromium version installed in the system.
Nevertheless other Chromium-based browsers that support extensions (like Opera and Vivaldi) can be launched using this target (with the addition of the `--chromium-binary` option):
[![Quick demo of the `web-ext run` used to run an extension on Chrome, Opera and Vivaldi](https://img.youtube.com/vi/L4sLn1OD7vM/0.jpg)](https://www.youtube.com/watch?v=L4sLn1OD7vM)
TODO:
> feat: Support chromium-based browsers as web-ext run targets

- package-lock.json
- package.json
- src/cmd/docs.js
This pull request change the npm dependencies to switch from [opn](npmjs.com/package/opn) (now deprecated) to [open](npmjs.com/package/open) (new npm package name for the same dependency).
This PR includes and supersedes #1679 (it includes the changes from #1679 and fixes the diff applied to the package-lock.json file).
> fix: Changed npm dependency from opn to open

- package.json
- src/cmd/build.js
- src/util/manifest.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test-util/test.manifest.js
Fixes #1013.
This PR doesn't require a change in package-lock.json, because I purposefully selected a version of strip-bom that was already depended upon via other dependencies. The latest version (4.0.0) does not differ in functionality compared to the chosen version (3.0.0).
> fix: Strip UTF-8 BOM before parsing manifest.json/messages.json

- src/util/promisify.js
- src/util/temp-dir.js
- tests/unit/test-firefox/test.remote.js
- tests/unit/test-util/test.promisify.js
This PR fixes some new flow-check errors detected by running flow 0.108.0
(fixes needed by #1588, to successfully run travis CI jobs).
> chore(flow): Fixed new flow-check errors detected by flow 0.108.0

- src/firefox/preferences.js
Fixes #1702 
Hey @rpl!
I hope you're doing well!
I believe this is the only change that is needed to fix this issue. Is that right?
Also, do I need to use a conditional statement to only set ```extensions.logging.enabled``` to ```true``` when ```--browser-console``` is sent as a parameter when running web-ext?
Thanks!
> feat: Enabled by default visibility of extension pages and content scripts logs in the BrowserConsole

- package.json
- scripts/develop
- scripts/lib/mocha.js
- scripts/test
This PR workarounds the issue described in #1739 by skipping the code coverage collection on travis windows workers.
> test: Disabled code coverage collection on Travis windows workers

- package.json
- src/cmd/sign.js
This PR is related to two commit to be merged on the patch-releases-3.2.x branch (and so it is not meant to be merged on master) and then released on npm as part of a new 3.2.1 patch release:
- fix: Backported longer sign command timeout from sign-addon 1.0.0
- chore: Bump package version for release 3.2.1
(As a side note, the patch-releases-3.2.x currently contains 1 commit, the fix from #1742 backported to this branch to fix the nyc-related failures in the travis windows workers).
> fix: Backport longer sign command timeout and bump package version for release for 3.2.1

- .nsprc
Backported #1750 into the patch-release-3.2.x branch.
> chore(audit): Add handlebars advisory to nsprc ignore list (#1750)

- .nsprc
- package-lock.json
This PR prevents the handlebars-related npm audit failure in CI job, by fixing the handlebars sub-dependencies in the package-lock's dependency tree.
The changes to the package-lock have been generated by running npm audit fix using the last npm released version.
Fixes #1764
> chore: Updated package-lock file to prevent handlebars-related npm audit failure

- src/firefox/preferences.js
This confused me quite a lot, see
https://bugzilla.mozilla.org/show_bug.cgi?id=1598947
Changing the default behavior of target="_blank" is quite arbitrary and
unexpected, IMO.
> fix: Reset browser.link.open_newwindow on desktop Firefox too.

- src/program.js
- tests/functional/test.typo.run.js
- tests/unit/test.program.js
> feat(cli): suggest matching commands

- src/extension-runners/chromium.js
- tests/unit/test-extension-runners/test.chromium.js
> fix: Removed default '--mute-audio' flag for chromium

- README.md
While going through the README I discovered that the link `http://olympia.readthedocs.org/en/latest/topics/api/signing.html` was not working. I figured similiar to the `linting`, the addon should be linked here. 
If this is not the case please feel free to close the PR.
> docs: Fixed link to signing addon

- src/extension-runners/chromium.js
Fixes #1779 
The underlying issue is (unsurprisingly) a race, between the WebSocketServer starting up and the chromium extension runner setup moving on to generate the extension used to control the chromium instance (which needs to retrieve the WebSocketServer address and port to interpolate them into the extension sources).
If the WebsocketServer is not yet listening, calling `wss.address()` would return `undefined`, and the rest of the chromium runner setup fails.
> fix: chromium runner async setup should wait for the WebSocketServer to be listening

- .npmignore
- package.json
- scripts/lib/config.js
- scripts/test-functional
This PR does exclude from the released npm package any asset that isn't needed in production (like we did for the sign-addon dependency in mozilla/sign-addon#402).
Besides that, this PR also change the test-functional script to use `npm pack` to run the production mode functional tests on the same package we would release on npm (without the need to keep a separate list of files to include).
> fix: npm release should only include production assets

- package-lock.json
- package.json
- src/program.js
- tests/unit/test.program.js
This PR:
- contains some small changes needed to fix #1707 (and to cover the expected behavior with additional assertions) 
- reverts a workaround introduced in #306 to fix #304 (and replaces it with a workaround that works for both #304 and [the failure triggered by yargs 15.0.2 in #1760 on the --no-config-discovery test case](https://travis-ci.org/mozilla/web-ext/jobs/627342145#L942-L954))
- update yargs to v15.0.2 and supersedes #1760
> fix(deps): update dependency yargs to v15.0.2

- webpack.config.js
This is to support use of `import ... from 'yargs/yargs'` in #1812
This would also have been the proper fix instead of #383 .
> fix: Allow import of external modules without bundling

- src/program.js
- tests/functional/test.cli.run.js
- tests/unit/test.program.js
This PR contains another possible approach to fix #793 (as an alternative to disabling the yargs strict parsing as in #1810
> fix: Remove WEB_EXT_* env vars not supported by the selected web-ext command

- src/cmd/run.js
- src/extension-runners/firefox-android.js
- src/program.js
- src/util/adb.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.firefox-android.js
- tests/unit/test-util/test.adb.js
- tests/unit/test.program.js
This pull request applies the following tweaks to make it easier to test a webextensions on a GeckoView-based browsers:
- Added Fenix and GeckoView to the auto-detected APK names (so that the user doesn't need to explicitly select the APK if Fenix is the only installed one)
- Exposed the `--adb-discovery-timeout` parameter (already supported internally but never exposed to as a cli option, it can be used to change the maximum time to wait for the remote debugging server discovery)
- Added a new `--firefox-apk-component` cli option (needed to make it easier to use `web-ext run` with other custom GeckoView-based apps, e.g. a user may add `--firefox-apk-component GeckoViewActivity` to run an extension on the geckoview_example)
- ~~Added a new --fennec-mode boolean parameter (which the user …
> feat: Added fenix support to the firefox-android extension runner

- src/firefox/remote.js
- tests/functional/fake-amo-server.js
- tests/functional/fake-firefox-binary.js
- tests/unit/test-firefox/test.remote.js
When `web-ext run` starts, the following prompt shows briefly on macOS:
> Do you want the application "node" to
> accept incoming network connections?
This is because we use `listen(0)` to find a port, and by default, this
method listens on any network interface.
Since we are only looking for free ports and not network connections,
limit `listen()` to localhost only.
> fix: Use local port to avoid triggering the firewall

- .travis.yml
The travis config that we are currently use is failing to deploy a tagged release on npm:
- https://travis-ci.org/mozilla/web-ext/jobs/649392805#L283-L284
I've been looking for clues about this issue in the travis forum and bug tracker, and it looks that it is an issue that other projects are also being triggering recently, e.g. it seems the same issue reported and discussed in the following posts from the travis forum:
- https://travis-ci.community/t/build-config-validation-using-api-key-breaks-npm-deployments/
- https://travis-ci.community/t/npm-deploy-failed-missing-api-key-but-i-have-set-it/
The workaround suggested (disabling the build validation from the Travis settings ui) doesn't seem to work for our repo.
This pull request is about trying another possible approach to fix the …
> chore(travis): Ported deploy config to dpl v2

- package-lock.json
- package.json
- webpack.config.js
There is already an existing npm package that does what I have implemented in #1634 and #1813 .
> chore: Replace custom externals with webpack-node-externals

- .nsprc
- package-lock.json
- package.json
- src/extension-runners/chromium.js
- src/util/artifacts.js
- tests/unit/test-extension-runners/test.chromium.js
This pull request contains some patches needed to update some dependencies (the one that have already released a new version that doesn't depend from the affected minimist release anymore) and temporarily add minimist to the nsprc's exceptions list.
We need to land these fix asap, to prevent all PR's CI jobs to be marked as failures because of this.
I'll also file a follow up bug to remove that url from the exceptions list as soon as possible
NOTE:
- this PR is meant to be landed without squashing the 4 commits.
Fixes #1863
Fixes #1845 
Fixes #1847
> fix: CI failures due to the audit-deps task

- src/firefox/remote.js
- tests/functional/fake-firefox-binary.js
- tests/unit/test-firefox/test.remote.js
Fixes #1884.
- Firefox 77+ requires `getRoot` because `listTabs` was removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1618691
- `getRoot` is supported since Firefox 55, with https://bugzilla.mozilla.org/show_bug.cgi?id=1352157
- I still added a `getList` fallback to not unnecessarily breaking backwards compatibility, so this is a safe patch for a minor release.
> fix: use getRoot request to support Firefox 77+

- src/firefox/preferences.js
Disable data reporting and the annoying notification that you can recognize in the screenshot:
> Disable data reporting and “Choose what I share” notification

- src/util/adb.js
- tests/unit/test-extension-runners/test.firefox-android.js
In addition to Fenix support (#1834), we'd like to add Reference Browser as well. 🙂
> feat: Add reference browser support to the firefox-android extension runner (#1870)

- .nsprc
- package-lock.json
- package.json
This PR contains:
- update yargs to version v15.3.1 (supersedes #1859, and also seems to fix #1282 due to upstream changes)
- removes conventional-changelog-cli (a devDependency that isn't actually used, we just missed to remove it when we migrated to new commitlint packages)
- temporarily add yargs-related advisory to nsprc to prevent failures on all CI jobs (unfortunately commitlint didn't released an update yet, but after this change none of the dependencies uses the vulnerable yargs-parser version and so web-ext is not going to propagate the vulnerable yargs-parser version to projects that use web-ext as an npm dependency)
> fix: Update yargs and prevent npm audit deps failures on CI

- src/cmd/build.js
- src/program.js
- tests/functional/test.cli.build.js
- tests/unit/test-cmd/test.build.js
- tests/unit/test.program.js
Fixes #1335. Based off #1741 and its review comments.
Questions:
- Does `-n` make sense as a single letter filename option? (`n` for name) I'm happy to add that or keep it as-is.
- Is there a reason why we [can't specify a directory path](https://github.com/mozilla/web-ext/pull/1741/files#r348005562)? I could see dying if the path specified doesn't exist, but I'm not sure why we can't write to a different directory.
- The code, as written, changes the `@` in the name to an underscore `_` (`minimal-example_web-ext-test-suite`. Is that expected? Should we allow for people to name the file what they want, if they pass in a flag (or warn that their name doesn't follow certain conventions)?
JavaScript isn't my strong suit; please review accordingly :)
> add --filename option to specify a filename template

- package.json
I did remove conventional-changelog-cli in #1902, but I did forgot that it was actually used in this npm script.
Given that I do run this script only when we are going to release a new version, I think that we can actually opt to run it using npx to avoid having it as a dev dependency for anyone would clone the repo to develop a patch.
> chore: Fix missing conventional-changelog script when running npm run changelog

- package-lock.json
- package.json
- src/extension-runners/chromium.js
- tests/unit/test-extension-runners/test.chromium.js
This pull request does supersede #1904.
Besides including the renovatebot changes from #1904 it is also:
- fixing incompatibilities between the properties exported in chrome-launcher v.0.13.3 and what extension-runners/chromium.js is using internally
- adding a new default flag included in v.0.13.3 into the test.chromium.js unit test
> fix(deps): update dependency chrome-launcher to v0.13.3 and adapt chromium extension-runner and defaultFlags test case

- src/util/adb.js
- tests/unit/test-util/test.adb.js
This PR fixes https://github.com/mozilla/web-ext/issues/1891 to add support for extensions loaded on android build variants.
Tested using:
```
web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.reference.browser.debug --firefox-apk-component=org.mozilla.reference.browser.BrowserActivity
web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.fenix.performancetest --firefox-apk-component=org.mozilla.fenix.HomeActivity
```
> fix: Enable extensions to load on android build variants

- package-lock.json
- package.json
This PR fix the npm audit failures currently being triggered during the CI jobs by:
- applying fixes to the package-lock.json by running npm audit fix
- upgrade @commitlint dev dependencies to version 9.1.1
> fix: npm audit failures

- package.json
This PR supersedes #1914 
It looks that `stream-to-promise` has been added as part of #744 but it is unused in that pull request (and we never used anywhere in the web-ext sources in the meantime).
> chore(deps): Removed unused stream-to-promise from the package.json dependencies

- src/cmd/run.js
- src/extension-runners/firefox-android.js
- src/program.js
- src/util/adb.js
- tests/unit/test-extension-runners/test.firefox-android.js
- tests/unit/test-util/test.adb.js
This pull request includes the changes from #1866 rebased on a recent tip of the web-ext main development branch with the following additions:
- renamed the new CLI option to --adb-remove-old-artifacts
- minor cleanup of the firefox-android.js module (folded the `adbOldArtifactsDir` method added in #1866 into the existing `adbPrepareProfileDir` method)
- some additional tweaks and cleanups to the new test cases
> fix: Detect old artifacts dirs on adb device, remove automatically using the new --adb-remove-old-artifacts cli option

- .flowconfig
- src/util/manifest.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-extension-runners/test.firefox-desktop.js
- tests/unit/test-util/test.manifest.js
Fixes #1901 
This PR includes and supersedes #1944 
- the first patch contains a squashed version of #1944 as submitted by the author (I did preserve Lusito as the author of that patch because it did change enough from the PR it was originally based on), 
- the second patch applies some small tweaks to:
- better match Firefox behavior (and some additional test case to cover the expected behaviors)
- fix some new flow typecheck errors (due to the updated flow version)
- small tweaks suggested in the last round of review comments
This PR also enable the optional chaining support in the flow config file.
> fix: web-ext should look for the extension id in browser_specific_settings and fallback to applications

- package-lock.json
All recently opened pull request are failing on CI due to a npm audit failure (related to the bl npm sub-dependency, inherited through firefox-profile direct npm dependency).
This patch contains the changes applied to the package-lock.json file by running `npm audit fix`.
> chore: Fix npm audit failures in CI job with changes to package-lock from 'npm audit fix'

- package-lock.json
- package.json
- src/util/adb.js
Fixes #2025
Some notes from some additional checks I did:
- The developer working on the replacement package @devicefarmer/adbkit is also part of the organization under which the adbkit package was developed, and the new @devicefarmer/adbkit seems to be actively maintained as discussed in the issue linked above.
- I also looked to the diff between the 3 adbkit/adbkit-* packages we are currently using and the 3 related package under the new devicefarmer github organization (both in their original coffeescript sources and the resulting transpiled js code) and the changes are minimal, matching what we would expect from a patch release, and nothing that should change the behavior of the code that is already using the adbkit package in web-ext.
- To be totally fair, there is some small changes …
> fix(deps): Switch from adbkit to @devicefarmer/adbkit npm package

- src/extension-runners/index.js
- tests/unit/test-extension-runners/test.extension-runners.js
This PR does apply a small change to the `defaultReloadStrategy` helper function to make sure that we do catch the rejection that `extensionRunner.reloadAllExtensions may have triggered (and then log the error as a warning, and the error stack as an additional debug level log).
The new behavior is going to:
- fix the new failures triggered by the related test case on mocha 8.2.0 (and unblock #2052 for merging, currently this issue triggers failures on the CI)
- prevent newer nodejs version from exiting the process because of an unhandled rejection (which in the current nodejs versions is just logged on the console, but in future nodejs version this is meant to make the entire nodejs process to exit with error)
> fix: defaultReloadStrategy should catch extension reloading errors

- .eslintignore
- .flowconfig
- flow-typed/README.md
- flow-typed/chrome-launcher.decl.js
- flow-typed/firefox-client.decl.js
- flow-typed/firefox-profile.decl.js
- flow-typed/watchpack.decl.js
- flow-typed/ws.decl.js
- package.json
- src/cmd/build.js
- src/cmd/docs.js
- src/cmd/sign.js
- src/extension-runners/chromium.js
- src/extension-runners/firefox-android.js
- src/extension-runners/firefox-desktop.js
- src/extension-runners/index.js
- src/firefox/index.js
- src/util/artifacts.js
- src/util/logger.js
- src/util/temp-dir.js
- src/util/zip-dir.js
- tests/functional/common.js
- tests/unit/helpers.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.chromium.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test.web-ext.js
This PR contains a number of changes needed to pass the flowtype checks on flow >= v0.132.0 (see #2003).
Most of the changes are only applied to the flow type signatures, but for some of the flowtype errors I opted to make some small changes on the implementation side (when it did look more appropriate).
Many of the new flowtype checks errors in #2003 are related to the dependencies, it looks that more recent flow versions are detecting when the types used are coming from a dependency that isn't typed using flow and the resulting types are all going to degrate to `any`.
Unfortunately the npm modules that are triggering these flowtype errors do not have their own flowtype declarations, and there isn't a third party one in the flow-types repository neither.
The easiest approach seems to be …
> chore: Fix on flow type signature to pass type checking on flow >= v0.132.0

- src/cmd/run.js
- src/program.js
- tests/unit/test-cmd/test.run.js
> feat: Added --profile-create-if-missing option

- src/program.js
- tests/functional/test.cli.nocommand.js
- tests/unit/test.program.js
This PR contains some minor changes to make sure we do accept the --no-input global cli option as documented and that it is parsed into the noInput boolean option the web-ext commands expects (plus a new test case to make sure we do not regress again on future updates of the yargs npm dependency).
Fixes #1860
> fix: Accept the --no-input global cli option and ensure it is parsed into a noInput boolean option

- package-lock.json
- package.json
- Supersedes #2072
- Avoids to downgrade the lockfile to version 1
It looks that the unexpected change in #2072 is due to using npm < v7, which will downgrade automatically the lockfile to version 1,
see this fragment from the npm source in the v6 branch:
- https://github.com/npm/cli/blob/39a25ae560d17393b2a7b8fbc2abc424654604b7/lib/install/read-shrinkwrap.js#L28-L30
This PR avoid the unexpected big package-lock.json by using npm v7 (`npx npm@7 install --package-lock-only`) locally to generate the minimal package-lock.json diff that we were expecting to see in #2072.
> chore(deps): update dependency flow-bin to v0.138.0

- src/cmd/run.js
- tests/unit/test-cmd/test.run.js
Follow up to #2064 based on @rpl's [comment](https://github.com/mozilla/web-ext/pull/2064#discussion_r518873064).
Throws error if `profile-create-new-if-missing` option used without `firefox-profile` or `chromium-profile`.
> feat: threw error if profile-create-new-if-missing used without profile

- .circleci/config.yml
Increase the default mocha timeout (same as #2099, which seems to have been enough to fix the intermittent failures for the windows test job, but extended to the non-windows jobs, because they have been also failing intermittently for the same reason).
> chore(ci): Increased default mocha timeout on functional tests ci job step

- tests/unit/test.program.js
For example, from a GitHub source tarball archive
Background: I'm the maintainer of [web-ext](https://archlinux.org/packages/community/any/web-ext/) package on Arch Linux, and I chose GitHub source tarballs (e.g., https://github.com/mozilla/web-ext/archive/5.5.0/web-ext-5.5.0.tar.gz) instead of the full git repository for building that package for saving disk space and a little time when building on Arch Linux's shared build server.
> test: Skip unit tests for git commit info in web-ext version when tests are not running from a git repository

- package.json
This PR does explicitly set npm engine compatibility to be strictly < v7
This should be hopefully be enough to prevent renovatebot to try to upgrade our lockfile to `lockfileVersion: 2`, as it seems to result in a lockfile incompatible with npm v6 and as a side effect it does make all recent CI jobs related to renovatebot PR to fail on the `npm ci` step (as described in https://github.com/mozilla/web-ext/pull/2142#issuecomment-772584368).
I double-checked locally that even if the npm engine required has to be strictly < v7, `npx npm@7 ci` is still completing successfully with the `lockfileVersion: 1` (and just printing a warning to mention that the npm version being used is not officially compatible with the web-ext package).
Unfortunately we can only be 100% sure that this change is …
> chore(npm): Required npm to be strictly < v7 in package.json (fixes #2145)

- package-lock.json
- package.json
- src/firefox/rdp-client.js
- src/firefox/remote.js
- tests/unit/helpers.js
- tests/unit/test-firefox/test.rdp-client.js
- tests/unit/test-firefox/test.remote.js
This PR contains a new `src/firefox/rdp-client.js` module that replaces the subset of feature we do use in web-ext from the unmaintained dependencies firefox-client and node-firefox-connect (and additional  unit tests to cover this new module).
By removing the firefox-client npm package from the dependencies we do also avoid one of the deprecation warnings related to `js-select@0.6.0` being logged when the web-ext package is installed by a user:
```
npm WARN deprecated js-select@0.6.0: Package no longer supported. Contact support@npmjs.com for more info.
```
> fix: Replaced unmaintained dependencies firefox-client and node-firefox-connect

- src/cmd/run.js
- src/extension-runners/index.js
- src/program.js
- src/watcher.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test.program.js
- tests/unit/test.watcher.js
Fixes #2104 
This allows passing multiple paths to `--watch-file` in order for `web-ext`. It tweaks the current tests to address the changes and make sure they still pass.
> feat: enabled watching multiple files via `--watch-file`

- package-lock.json
- package.json
- tests/setup.js
This PR does remove the explicit @babel/polyfill dependency (which is how we get the core-js@2 package as a transitive dependency).
This issue is part of the fixes needed for #2130 
I was originally planning to replace it with a direct core-js@3 dependency, but at a first glance I'm not really sure that we do actually need it for the ecmascript features that we are actually using (and the one already supported by nodejs releases officially supported), and so I opted to just remove the @babel/polyfill dependency for now.
> chore: Removed  deprecated @babel/polyfill package from web-ext npm dependencies

- src/program.js
> fix: Move filename from global to build command option

- tests/unit/test.watcher.js
Rewrote watchChange to make use of async-await:
https://github.com/mozilla/web-ext/blob/629aa142a6e643977fe6c94eb3f9d1fed8c6e3f0/tests/unit/test.watcher.js#L22-L103
> chore: Rewrote watchChange to make use of async await

- .circleci/config.yml
- package.json
This PR does bump the minimum nodejs version supported to v12 (would likely still work for now on nodejs v10 but it will print a warning when installed from npm, with yarn the user will have to explicitly pass the yarn CLI option to ask yarn to allow installing the package without enforcing the mininum nodejs version).
Along with bumping the minimum supported version, it does also add nodejs v15 to the nodejs versions we do run as part of the CI jobs (which is meant to be replaced with nodejs 16 once it will be released).
> fix: Bump minimum nodejs version supported to v12

- CONTRIBUTING.md
The contributor docs contain a link to issues with a `good first bug` label that no longer exists. This PR fixes the URL to point to the updated label `contrib: good first bug`.
> docs: fix URL for good first bug label

- src/util/adb.js
- tests/unit/test-extension-runners/test.firefox-android.js
- tests/unit/test-util/test.adb.js
This fixes #2173.
On Android 11, Fenix is no longer requesting access to the entire `/sdcard/` and uses more fine grained permissions now. web-ext was still assuming it did have permission.
To fix this, we use another directory, `/data/local/tmp/` that we do have access to. I think this directory is used by Android Studio and the rest of the official Android toolchain.
```
$ web-ext run -t firefox-android --android-device=192.168.3.70:5555 --firefox-apk org.mozilla.fenix
Running web extension from /home/home/WebstormProjects/darkreader/debug-firefox
Selected ADB device: 192.168.3.70:5555
Stopping existing instances of org.mozilla.fenix...
Old artifacts directories have been found on 192.168.3.70:5555 device. Use --adb-remove-old-artifacts to remove them automatically.
Starting …
```
> fix: Support Android 11

- .nsprc
- package-lock.json
- package.json
- lodash security advisory: fixed in package-lock.json using `npm audit fix`
- underscore sec advisory: removed doctoc from explicit dependencies (added npx to the npm script, anyway we don't run this in CI jobs and we don't run it that often) 
- hosted-git-info sec advisory: temporarily added to nsprc exception list (it is used in @commitlint and eslint-plugin-import transitive dependencies)
> chore: Fixed npm audit issues to unblock PR with failing CI jobs  

- package-lock.json
This PR includes (and supersedes): #2259,  #2260, #2261, #2262, #2263
The 3 fixes need to be in a single pull request because otherwise the npm-audit-deps step of the CI jobs would still fail.
> chore: npm audit failures triggered by trim-newlines, glob-parent and normalize-url sub-dependencies.

- .circleci/config.yml
test.lib.imports.js is failing intermittently with a slightly higher intermittency, likely due to the fact that we do run (on purpose) npm ci using the last npm version (since #2146) but the test function are using the npm version installed by default along with the nodejs version being tested.
> chore: Increased test-functional mocha timeout to reduce test.lib.imports.js intermittency

- CONTRIBUTING.md
babel-core/register has been replaced by @babel/register in babel 7
> docs: Update testing command documentation

- src/extension-runners/firefox-android.js
- tests/unit/test-extension-runners/test.firefox-android.js
Fixes #2304
For Fenix we don't need the WRITE_EXTERNAL_STORAGE permission to be granted:
- it was required for Fennec because `web-ext run` was also running it in a separate temporary profile as we do on desktop
- but Fennec doesn't support that and so the WRITE_EXTERNAL_STORAGE permission isn't really necessary
- We still need the READ_EXTERNAL_STORAGE permission to have been granted, to allow Fennec to load the xpi file that `web-ext run` uploads to the android emulator or device
TODO:
> fix: Fenix does not require WRITE_EXTERNAL_STORAGE permission to be granted

- src/program.js
fixes #2332 , process of arriving at this change documented there
I did not make this change out of some sort of expertise in js dependency loading mechanisms, but by trial and error and eliminating the odd one out. I did however test this change in my personal project by modifying the downloaded npm artifact's code in the same way, and I ran `npm test` in this repo after this change too. If I understand [the author's comment](https://github.com/yargs/yargs/blob/main/yargs#L1) right, this change can't be harmful.
I'm willing to put in more time to work with you on proving this change fixes something, but please reach out with instructions then. I'll give you a live demo via a discord call if you want, or a repo to reproduce it on (which is already linked in the issue).
> fix(deps): fixed yargs import for yarn 3.x + pnp

- src/program.js
- Detects the terminal width (in characters) using `yargs.terminalWidth()`.
- Sets the generated `yargs` usage to wrap at the terminal width instead of at the default (maximum) 80 characters.
- Should improve `web-ext` readability by utilizing the full terminal window, when it is greater than 80 characters wide.
- In particular, `--help` output is improved.
- Testing would require a TTY emulator. Tests were added and removed due to build system tooling issues.
See
- https://yargs.js.org/docs/#api-reference-wrapcolumns
<details>
<summary>Before: (maximum) 80 characters wide</summary>
```text
Usage: web-ext [options] command
Option values can also be set by declaring an environment variable prefixed
with $WEB_EXT_. For example: $WEB_EXT_SOURCE_DIR=/path is the same as
--source-dir=/path.
To …
```
> feat: Wrap web-ext usage output at terminal width

- .nsprc
All CI jobs are currently failing on the "npm audit" step, due to a json-schema advisory introduced by `request` npm package through transitive dependencies originated by:
- addons-linter 3.23.0 through dispensary (which is actually already fixed in addons-linter >= 4.1.0 where the dispensary dependency has been merged into addons-linter project and `request` npm package replaced by `node-fetch`) 
- sign-addon (which does currently use `request` as one of its direct dependencies) 
This PR includes the following changes:
- Removed from audit ignore list old trim-off-newlines advisories.
- Added json-schema advisory to npm audit ignore list
This PR is mainly meant to allow us to unblock the CI jobs in the short run (and in particular to allow #2350 to pass all CI jobs and get rid of one of …
> chore: update npm audit ignore list

- src/extension-runners/chromium.js
> fix: Replace localhost with ipv4 to avoid ipv6 issue

- src/extension-runners/firefox-android.js
Small tweak to cover the "firefox-android extension runner" part of #2337 (similarly to how #2339 covers the web-ext side of the issue with the chromium extension runner issue on nodejs 17).
> fix: Set default adb host to 127.0.0.1 to prevent localhost resolution mismatch in nodejs 17

- .nsprc
Fixes #2358 (the json-schema transitive dependency has been updated to a non affected one by #2361).
> chore: Remove json-schema from .nsprc ignore list

- src/watcher.js
- tests/unit/test.watcher.js
Fixes #2249 
This is a rebase of #2259, with the same author metadata and no actual changes (the patch does still apply cleanly as is).
> fix: Improved debounce to prevent multiple extension reloads on consecutive file changes

- scripts/lib/mocha.js
this PR fixes the missing code coverage data (which was due to babel istanbul plugin not being activated through NODE_ENV env variable set to 'test').
> chore(test): Fixed missing coverage data

- src/cmd/run.js
- src/program.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test.program.js
This flag allows to enable the [Firefox Dev Preview for Manifest V3][get-involved] (at the moment, given that was my main use case). I've been light on testing but it covers enough. I don't think we need to be super fancy right now (personally).
[get-involved]: https://blog.mozilla.org/addons/2022/06/08/manifest-v3-firefox-developer-preview-how-to-get-involved/
> feat: introduce a --firefox-preview flag for 'web-ext run'

- .nsprc
- package-lock.json
This PR contains a fully refreshed package-lock.json (regenerated locally by removing both the existing node_modules and package-lock.json file and then re-running npm install using the last release npm version, `npx npm@latest install`) and clear old (and now unused) npm audit exceptions from the .nsprc file.
NOTE: this is just needed to clear a sec advisor that dependapot still detects due to the existing package-lock.json file (which is only used during development and in CI jobs and it isn't actually included nor used in the package released on npm).
> chore: package lock refresh

- package-lock.json
Fixes npm audit failure due to sec-advisory from moment transitive dep (e.g. [like in this CI job failure triggered by the npm audit workflow step](https://app.circleci.com/pipelines/github/mozilla/web-ext/1541/workflows/bac65f22-6e78-4da3-9dc9-c02916c3d17a/jobs/6241/parallel-runs/0/steps/0-117)).
> chore: updated package-lock file

- src/program.js
- tests/unit/test.program.js
The --firefox-preview web-ext option we introduced in v7.1.0 should not default to mv3 if it wasn't explicitly passed as an option (either on the command line or through the web-ext config file).
Unfortunately setting a default value through the yargs `default` property will always set `argv.firefoxPreview` to `['mv3']` even when it is not explicitly passed, `demandOptions` set to `false` makes the cli option not mandatory but it doesn't ignore the default value.
This PR adds an additional test case to make sure that `argv.firefoxPreview` is `undefined` when not explicitly passed as an option, and a small tweak to program.js that make sure `argv.firefoxPreview` defaults to `['mv3']` if it was set to an empty array (and so when `--firefox-preview` was explicitly passed but without any …
> fix: firefoxPreview option should be set to mv3 only when explicitly requested

- package-lock.json
- package.json
babel-loader is an unused dev dependency since we have migrated the web-ext package into ESM module format, babel-loader used to be required in the mocha commands to make sure we were transpiling with babel the src/ modules, as part of the migration to ESM we replaced it with a small `tests/babel-loader.js` module included into the web-ext repository itself, which depends only on `@babel/core` and `testdouble` (and so babel-loader was not used anywhere anymore).
This PR also removes the `terser` npm package from the transitive dev dependencies (and so it is also fixing and superseding #2466).
> chore: Removed unused babel-loader dev dependency

- src/util/submit-addon.js
- tests/unit/test-util/test.submit-addon.js
closes #2493 - doesn't add session token auth (as the issue is currently describing) but instead abstracts the API auth into a separate class, so a consumer of this package could provide their own easily.
> make api auth more pluggable in submit-addon.js::Client

- src/cmd/lint.js
- src/program.js
- tests/unit/test-cmd/test.lint.js
Fixes https://github.com/mozilla/web-ext/issues/2484
---
This option (which defaults to 'mv3') will configure addons-linter to
lint MV2 and MV3 extensions when specified.
> feat: Add `--firefox-preview` option to the `lint` command

- src/cmd/sign.js
- src/program.js
- src/util/submit-addon.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-util/test.submit-addon.js
fixes #2504 + makes the base url constractor arg a `URL` in `Client` to be consistent with internal use in the class.
> Rename apiHost to amoBaseUrl

- src/cmd/run.js
- src/extension-runners/firefox-desktop.js
- src/firefox/index.js
- src/firefox/remote.js
- src/program.js
- tests/functional/fake-firefox-binary.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-firefox/test.remote.js
- tests/unit/test.program.js
This depends on bug [1787409](https://bugzilla.mozilla.org/show_bug.cgi?id=1787409) and aims at addressing issue #759.
> feat: Introduce webext run --devtools to open DevTools for the installed add-on right away.

- README.md
Fixes #2508 
---
This is needed because we don't have default exports OR default exports don't expose everything.
> docs: use namespace imports in README examples

- src/cmd/sign.js
- src/util/submit-addon.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-util/test.submit-addon.js
fixes #2491 - and could address #2490 (at least in part) by clearly stating the addon id after it's available from AMO.
> write id to file upon successful submission

- src/util/submit-addon.js
- tests/unit/test-util/test.submit-addon.js
fixes #2529 (+ quick fix for #2530)
> fix: building Client.apiUrl so `/api/v5/` isn't stripped off

- src/cmd/lint.js
- tests/unit/test-cmd/test.lint.js
Refs https://github.com/mozilla/web-ext/issues/2549
---
I'll update `web-ext run` in a different patch.
> feat: enable MV3 by default in `web-ext lint` command

- .nsprc
Fixes https://github.com/mozilla/web-ext/issues/2589
> chore: skip `fast-json-patch` npm audit failure

- src/program.js
Fixes #2546
This PR adds the missing type statement.
> fix missing type for channel parameter

- .nsprc
Fixes https://github.com/mozilla/web-ext/issues/2596
> chore: remove 'fast-json-patch' from the exclusion list in .nsprc

- src/program.js
- src/util/submit-addon.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-util/test.submit-addon.js
> add trailing slash to amo-base-url & enforce within submit-addon Client

- src/program.js
This documents the "deved" alias introduced in #1906, which was released in 4.3.0.
This feature was requested again at https://github.com/mozilla/web-ext/issues/2627 because the alias was not well-known.
> docs: document "deved" alias for "firefoxdeveloperedition"

- src/util/adb.js
- tests/unit/test-util/test.adb.js
Due to Android 13 changes described [here](https://developer.android.com/guide/components/intents-filters#match-intent-filter) which require activities to now match action and categories this PR updates the `.startActivity` to do this. 
Locally building and testing shows this to now work in Fenix as expected with the command:
`web-ext run -t firefox-android --adb-device DEVICE_ID_HERE --firefox-apk org.mozilla.fenix.debug --firefox-apk-component App`
> fix: Android 13 startActivity with correct intent action and category

- .nsprc
This PR adds tough-cookie (transitive dependency got through `sign-addon -> request -> tough-cookie`) to the nsprc file.
> chore(deps): ignore https://github.com/advisories/GHSA-72xf-g2v4-qvf3 (tough-cookie)

- src/cmd/sign.js
Fixes https://github.com/mozilla/web-ext/issues/2877
---
This will look like this:
```
❯ ./bin/web-ext.js sign --api-key="foo" --api-secret="bar"
Applying config file: ./package.json
IMPORTANT: web-ext v8 will introduce a new AMO submission API for signing and you might need to take actions when upgrading from v7 to v8. You can test this upcoming change now by specifying `--use-submission-api` to the `sign` command. If you want to keep using the API you are using now (via "sign-addon"), you must stay on v7.
[...]
```
> feat: warn web-ext v7 users about upcoming changes to the sign command

- src/cmd/sign.js
- src/program.js
- src/util/submit-addon.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-util/test.submit-addon.js
part of #2497 - supports uploading sources for versions
> implement source file upload

- README.md
Current link is broken. Updated with the working one.
> docs: update signing documentation link

- .nsprc
- CONTRIBUTING.md
- package-lock.json
- package.json
- src/cmd/sign.js
- src/program.js
- tests/functional/fake-amo-server.js
- tests/functional/test.cli.sign.js
- tests/unit/test-cmd/test.sign.js
> feat: remove sign-addon

- src/util/adb.js
- tests/unit/test-util/test.adb.js
On some devices with work profile enabled, `adb shell pm list packages` will fail with permission error.
Avoid reaching work profile and scan packages for the primary user instead.
> fix: Cannot find Firefox package on device with work profile

- src/cmd/sign.js
- src/util/submit-addon.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-util/test.submit-addon.js
Various minor improvements to output useful information when using `web-ext sign`.
```
$ ../web-ext/bin/web-ext.js sign --channel=listed --amo-metadata=metadata.json
Building web extension from /Users/william/projects/mozilla/test-ext
POSTing URL: https://addons.allizom.org/api/v5/addons/upload/
Waiting for Validation...
GETing URL: https://addons.allizom.org/api/v5/addons/upload/e3f6549d0c9a433fa1e06b5c2db55162/
GETing URL: https://addons.allizom.org/api/v5/addons/upload/e3f6549d0c9a433fa1e06b5c2db55162/
GETing URL: https://addons.allizom.org/api/v5/addons/upload/e3f6549d0c9a433fa1e06b5c2db55162/
Validation results: {
errors: 1,
warnings: 1,
notices: 0,
success: false,
[...]
message_tree: {},
ending_tier: 5
}
Validation failed.
FAIL
WebExtError: Validation failed, open the following URL …
```
> feat: improve CLI output of the sign command

- package-lock.json
- package.json
- src/cmd/config.js
- src/cmd/dump-config.js
- src/cmd/index.js
- src/config.js
- src/program.js
- src/util/logger.js
- tests/functional/test.cli.dump-config.js
- tests/functional/test.cli.run.js
- tests/functional/test.cli.sign.js
- tests/unit/test.config.js
- tests/unit/test.web-ext.js
This PR includes a small set of changes to:
- add support for loading config files in the ESM module format
- add guidance help message to UserError error messages raised when hitting parsing error because the config file is not in the nodejs instance expects it to be (e.g. either a .js config file in CommonJS format from a type module package, or a .js config file in ES module format from a type commonjs package)
- proposed addition of an additional command which does just print all config data loaded from the discovered files
Fixes #2604 
TODO:
> feat: Add support for config files in ES module format

- src/util/submit-addon.js
- tests/unit/test-util/test.submit-addon.js
Fixes https://github.com/mozilla/web-ext/issues/3030
---
See output in https://github.com/mozilla/web-ext/issues/3030
```
$ web-ext sign --channel=unlisted --amo-metadata=metadata.json --approval-timeout=0
Building web extension from /path/to/test-ext
Waiting for validation...
Waiting for approval and download of signed XPI skipped. When approved the signed XPI file can be downloaded from https://addons.mozilla.org/en-US/developers/addon/xxx/versions/123
```
```
$ web-ext sign --channel=unlisted --amo-metadata=metadata.json --approval-timeout=10
Building web extension from /path/to/test-ext
Waiting for validation...
Waiting for approval...
WebExtError: Approval: timeout exceeded. When approved the signed XPI file can be downloaded from …
```
> fix: Allow any positive integer in `--approval-timeout`

- package-lock.json
- package.json
This should allow users of the unreleased bleeding-edge version of web-ext to report the right version.
> fix: Bump version in package.json

- src/program.js
- tests/unit/test-cmd/test.sign.js
This PR removes out of date references to the `--use-submission-api` CLI flag.
> Fix references to removed CLI flag

- src/cmd/lint.js
- src/cmd/run.js
- src/program.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test.program.js
Fixes https://github.com/mozilla/web-ext/issues/3104
> fix: Remove --firefox-preview flag since we no longer use it

- src/util/adb.js
- tests/unit/test-util/test.adb.js
Backport to v7, see https://github.com/mozilla/web-ext/issues/3116#issuecomment-2133844621
> fix: Cannot find Firefox package on device with work profile (#2857)

- package-lock.json
- package.json
Backport-ish addons-linter and eslint updates to get their latest version in the v7 branch.
> chore: bump addons-linter to 6.28.0

- src/extension-runners/firefox-android.js
- src/firefox/preferences.js
- src/firefox/rdp-client.js
- src/program.js
- src/util/adb.js
I am reading the repo to learn something, but typos-lsp told me that there are some typos. So I think maybe I can make a pr.. and lsp said that there are some `async` keywords are missing.
> fix: typo and missed async keyword

- package-lock.json
- package.json
- tests/unit/test-extension-runners/test.chromium.js
Extracted from #2912, and replaces #3170.
> chore(deps): Upgrade chrome-launcher from 0.15.1 to 1.1.2

- src/cmd/run.js
- src/program.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test.program.js
Fixes #2993. 
Add a patch that turns the `run.js` sourceDir into an absolute path.
> fix: Resolve input sourceDir to absolute path

- src/cmd/run.js
The customPrefs alias was introduced in #1039 as a direct alias, but changed to a shallow copy in #2436 because the object was modified. These changes have been dropped in #3136 but the swallow copy remained.
This patch completes the cleanup by reverting to a direct alias.
> chore: Clean up unnecessary spread

- src/extension-runners/chromium.js
- tests/unit/test-extension-runners/test.chromium.js
Similarly to puppeteer/puppeteer#13010, 
Quoting @mathiasbynens:
> Summarizing the “why” here:  
The --disable-component-update command-line flag does two things: it disables component updates (desired) but it also prevents any bundled components from being initialised (undesired).
Disable this flag grant more flexibility, and it can always be disabled via the `web-ext run --arg option`
> feat: remove --disable-component-update from default args

- README.md
- package.json
- tests/fixtures/webext-as-library/helpers.js
> Export submit-addon via package.json

- src/util/submit-addon.js
- tests/unit/test-util/test.submit-addon.js
As a followup to #3250, this PR sets 'web-ext-lib' as a fallback when userAgentString property has not been explicitly set.
> chore: Ensure submit-addon exported methods fallbacks to 'web-ext-lib' userAgentString when not specified

- README.md
As a followup to #3250, this PR applies a few more tweaks to the README.md to suggest setting the userAgentString to a custom user agent (instead of following the convention used by the userAgent set by the web-ext cli tool).
In addition to that this PR explicitly mention webExt.cmd.sign (given it is part of the suggestion note associated to the submit-addon example) and expand the pre-existing note about the "limited support for the internal web-ext APIs" to clarify it.
> chore: Update README.md to suggest use of the userAgentString parameter

- src/program.js
Running `web-ext --help run` outputs this line:
```
--reload             Reload the extension when source files change.Disable with --no-reload.
```
I just added the missing whitespace.
> docs: Add missing whitespace in program.js

- tests/functional/common.js
- tests/functional/fake-firefox-binary.bat
- tests/functional/preload_on_windows.cjs
Fixes #3435.
I manually verified the fix locally in a Windows 11 VM following the STR in that issue. Before the patch, I get EINVAL when running `.\node_modules\.bin\mocha .\tests\functional\test.cli.run.js`. After the patch, the test passes.
> chore: Avoid EINVAL in fake-firefox-binary

- src/util/submit-addon.js
- tests/unit/test-util/test.submit-addon.js
Fixes #3418.
For context, see https://github.com/mozilla/web-ext/issues/3418#issuecomment-3049712239
> fix: Correct file name in web-ext submit in Node 24

- README.md
Fixed broken link in README.md for "Getting started with web-ext" documentation
> docs: Updated link to web-ext documentation
