mozilla/web-ext

- .babelrc
- .gitignore
- Gruntfile.js
- README.md
- bin/web-ext
- package.json
- src/main.js
- tasks/mochaTest.js
- tasks/webpack.js
- webpack.config.js
Fixes https://github.com/mozilla/web-ext/issues/1
> Scaffolding to run a command

- Gruntfile.js
- README.md
- package.json
- src/cli.js
- src/main.js
- tasks/clean.js
- tasks/webpack.js
- tests/.eslintrc
- tests/cli/test.cli-process.js
- tests/runner.js
- webpack.config.js
Fixes https://github.com/mozilla/web-ext/issues/2 and https://github.com/mozilla/web-ext/issues/12
> Add initial test for version number output

- .travis.yml
Fixes https://github.com/mozilla/web-ext/issues/3
> Add initial Travis CI config

- Gruntfile.js
- README.md
- package.json
- tasks/watch.js
- tasks/webpack.js
Fixes https://github.com/mozilla/web-ext/issues/14
> Watch files and run tests

- package.json
> chore(package): update babel-eslint to version 5.0.0

- tests/build/test.build.js
- tests/util.js
This no longer requires the caller to take responsibility for cleaning up temp dirs.
> Work with a temp dir more safely in the test suite

- package.json
> chore(package): update babel-core to version 6.6.0

- bin/web-ext
- src/cli.js
This PR contains a proposed fix for #99
> Fix ENOENT on running the --version cli option

- CONTRIBUTING.md
- README.md
Fix #91 
- Added `CONTRIBUTING.md` file
- Updated `README.md`
> Adding contributing.md & updating readme.md

- .jscsrc
- src/cmd/run.js
- src/errors.js
- src/firefox/index.js
- src/program.js
- src/util/is-directory.js
- tests/test-cmd/test.run.js
- tests/test-firefox/test.firefox.js
- tests/test-util/test.is-directory.js
- tests/test.errors.js
Fixes https://github.com/mozilla/web-ext/issues/69
> Run extension in a custom Firefox profile

- package.json
- src/firefox/remote.js
- tests/test-firefox/test.remote.js
This is required for https://github.com/mozilla/web-ext/issues/138
> Added remote Firefox reloading support

- src/program.js
> fix: Fixed error on unknown commands

- src/cmd/sign.js
- src/program.js
- tests/test-cmd/test.sign.js
> feat: Added --timeout option for signing

- src/program.js
- tests/test.program.js
* maybe fixes #161 but I'm struggling on how to test this
> log the version if verbose

- src/program.js
- tests/test.program.js
> fix: Fixed using env variables for non-global options

- src/cmd/build.js
- tests/test-cmd/test.build.js
> feat: Started ignoring node_modules folders by default

- package.json
Fixes https://github.com/mozilla/web-ext/issues/304
> fix: Configured yargs without boolean negation, fixed --no-reload

- tasks/mochaTest.js
This might address https://github.com/mozilla/web-ext/issues/335
> chore: Increase test suite time-out for Travis I/O

- tests/test-cmd/test.sign.js
Originally added in https://github.com/mozilla/web-ext/commit/fdf3d3b6
> chore: fix typo

- .travis.yml
Specifically, this should fix tag checkouts (which are detached heads). Example: https://travis-ci.org/mozilla/web-ext/jobs/143159184
> chore: Fix linting from TravisCI (again)

- src/firefox/index.js
Something not covered by unt tests :D
> Fix `web-ext run`

- src/cmd/lint.js
fallout from https://github.com/mozilla/web-ext/pull/372
> chore: fix dependency injection

- .eslintrc
- src/cmd/build.js
- src/cmd/lint.js
- src/cmd/run.js
- src/cmd/sign.js
- src/firefox/index.js
- src/firefox/remote.js
- src/program.js
- src/util/logger.js
- tests/unit/helpers.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-firefox/test.remote.js
- tests/unit/test.program.js
> Require spaces around infix operators

- .github/ISSUE_TEMPLATE.md
Fixes https://github.com/mozilla/web-ext/issues/514
> chore: Added an issue template

- .travis.yml
Refactored travis.yml and cleaned changelog if statements #526
> refactor: Cleaned changelog if statements

- src/program.js
- tests/unit/test.program.js
> refactor: rename the run test helper to execProgram

- package.json
- tests/functional/common.js
- tests/functional/test.cli.build.js
- tests/functional/test.cli.lint.js
- tests/functional/test.cli.nocommand.js
- tests/functional/test.cli.run.js
- tests/functional/test.cli.sign.js
> fix: format output for failing functional tests to make it more readable

- package.json
> chore(package): update eslint-plugin-flowtype to version 2.28.2

- src/program.js
Fixes https://github.com/mozilla/web-ext/issues/689
> fix: Fixed a hang on Windows with `web-ext --verbose ...`

- tasks/travis-pr-title-lint.js
This PR uses the `git-merge-base` command to get the sha1 of the branching point and `'git rev-list --no-merges` to be able to not include the "hidden github merge commit" while it is counting the number of commits in a pull request.
> Lint commit message on single-commit branches

- tasks/travis-pr-title-lint.js
This PR should finally fix the intermittency of the "pull request title" linting ;-)
> chore: Fixed the intermittent empty pull request title failures

- package.json
> chore(package): update babel-core to version 6.21.0

- src/cmd/run.js
- src/firefox/remote.js
- tests/unit/test-firefox/test.remote.js
Fixes #796
Hey, this is my first pull request ever. This was the best solution I could think of but I bet there are better ways to solve this issue.
> feat: make reload desktop notifications more concise

- package.json
> fix(package): update bunyan to version 1.8.7

- tests/unit/test.program.js
> test: Fix test failure in non-English locales

- package.json
> chore(package): update conventional-changelog-cli to version 1.3.1

- package.json
> chore(package): update conventional-changelog-lint to version 1.1.8

- package.json
> fix(package): update addons-linter to version 0.18.1

- CONTRIBUTING.md
> docs: Update CONTRIBUTING.md with release schedule

- src/firefox/preferences.js
> fix(firefox-preferences): Removed firefox preferences related to automated testing

- .travis.yml
- README.md
- appveyor.yml
See https://github.com/mozilla/addons-linter/pull/1272
Fixes https://github.com/mozilla/web-ext/issues/887
> feat: Drop testing on node4

- package.json
Sorry, forgot to include this...
See https://github.com/mozilla/web-ext/pull/942
> feat: Increase minimum node version in manifest

- src/cmd/build.js
- src/cmd/docs.js
- src/cmd/lint.js
- src/cmd/run.js
- src/cmd/sign.js
- src/program.js
- tests/unit/test-cmd/test.lint.js
- tests/unit/test.program.js
> fix: set runAsBinary according shouldExitProgram for lint command

- src/cmd/build.js
- src/program.js
- tests/unit/test-cmd/test.build.js
Fixes https://github.com/mozilla/web-ext/issues/68
Done some changes to fix the issue
> feat: Added check for existing package and a new --overwrite-dest CLI option in build command

- package.json
> chore(package): update grunt-flowbin to version 0.2.0

- package.json
> fix(package): update addons-linter to version 0.22.2

- src/cmd/run.js
- tests/unit/test-cmd/test.run.js
Here is my version of #921 ~~which doesn't work with node v7.10.0~~ (it works now)
> fix: unable to suspend web-ext when running in interactive mode

- tests/unit/test-util/test.desktop-notifier.js
- tests/unit/test-util/test.logger.js
- tests/unit/test-util/test.updates.js
This is my first pull request. I changed some chai asserts to sinon asserts.
Part of https://github.com/mozilla/web-ext/issues/972
> feat: Added sinon asserts to test.updates.js

- tests/unit/test-cmd/test.build.js
- tests/unit/test-cmd/test.docs.js
- tests/unit/test-cmd/test.run.js
- tests/unit/test-extension-runners/test.firefox-desktop.js
- tests/unit/test.program.js
Some more sinon assertions for review.
> chore: added some sinon assertions

- package.json
> chore(package): update eslint-plugin-flowtype to version 2.35.0

- package.json
> chore(package): update flow-bin to version 0.51.1

- src/cmd/run.js
- tests/unit/test-cmd/test.run.js
following up https://github.com/mozilla/web-ext/pull/1019#issuecomment-319805833
> feat: run cmd accept custom manifest parser

- package.json
> chore(package): update webpack to version 3.5.3

- package.json
> fix(package): update addons-linter to version 0.24.0

- src/program.js
> fix: Don't show the command in error messages

- tests/unit/test-cmd/test.lint.js
- tests/unit/test.program.js
@kumar303 Here are some more sinon assertions.
> chore: sinon assertions for test.program.js and test.lint.js

- .travis.yml
I think this will work but we'll have to cut a bug fix release to fully test it. If this works I'll file an issue to follow-up with some better safety checks so it doesn't happen again.
> fix: Fix deploy script so that it always publishes a production build.

- README.md
Fixes https://github.com/mozilla/web-ext/issues/381
> docs: Document NodeJS programmatic usage

- tests/unit/test-cmd/test.sign.js
- tests/unit/test-firefox/test.remote.js
- tests/unit/test-util/test.artifacts.js
- tests/unit/test.program.js
> test: chunk of chai assertions changed to sinon assertions

- tests/unit/test-cmd/test.build.js
- tests/unit/test-cmd/test.lint.js
- tests/unit/test.watcher.js
> test: changed chai assertions to sinon assertions

- tests/unit/test-extension-runners/test.firefox-desktop.js
- tests/unit/test-firefox/test.firefox.js
- tests/unit/test-firefox/test.remote.js
> test: chai assertions to sinon assertions

- package.json
> fix(package): update regenerator-runtime to version 0.11.1

- src/config.js
- src/program.js
- tests/unit/test.config.js
- tests/unit/test.program.js
Fixes https://github.com/mozilla/web-ext/issues/1151
> fix: Fix config parsing issues

- package.json
> chore(package): update yauzl to version 2.9.1

- package.json
> fix(package): update bunyan to version 1.8.12

- package.json
> chore(package): update coveralls to version 2.13.3

- README.md
- src/cmd/sign.js
- tests/unit/test-cmd/test.sign.js
Original patch by @yfdyh000 
Updates all terminology according to https://wiki.mozilla.org/Add-ons/Terminology
> docs: Update all references to "WebExtensions"

- package.json
> fix(package): update es6-error to version 4.1.1

- package.json
> fix(package): update firefox-profile to version 1.1.0

- package.json
> chore(package): update grunt-webpack to version 3.0.2

- src/util/adb.js
Fixed a missing space in adb permission error
> fix: Fixed typo in adb permission error

- src/config.js
- tests/unit/test.config.js
Removed unnecessary colon in config error
> fix: Removed unnecessary colon in config error

- package.json
> fix(package): update node-notifier to version 5.2.1

- package.json
> fix(package): update source-map-support to version 0.5.2

- package.json
> fix(package): update addons-linter to version 0.36.1

- package.json
> chore(package): update eslint-plugin-flowtype to version 2.46.1

- package.json
- src/firefox/remote.js
closes: https://github.com/mozilla/web-ext/issues/1282
by implementing:
https://github.com/mozilla/web-ext/issues/1282#issuecomment-371538235
cc: @rpl
> fix: Fixed "web-ext run" regression on Firefox 60

- src/util/temp-dir.js
- tests/functional/common.js
- tests/functional/test.cli.nocommand.js
It shoudl be a string.
This will fix #1129 partially.
> fix: Fix the second argument of TempAddonCallback

- package.json
- src/util/manifest.js
- tests/unit/test-util/test.manifest.js
> fix: Allow comments in manifest.json

- src/extension-runners/firefox-android.js
- src/util/adb.js
- tests/unit/test-util/test.adb.js
This commit is to allow extension development on custom forks of
firefox for android, not just on firefox and fennec
> feat: Allowed detection of given firefox APK

- package.json
> fix(package): update addons-linter to version 1.3.8

- src/cmd/sign.js
- src/program.js
- tests/unit/test-cmd/test.sign.js
Identical to #1250, but with a simplified test requested by @kumar303.
Added release channel as optional sign parameter. Fixes #877.
> feat: Added release channel as optional sign parameter (simple test)

- README.md
> Remove reference to jpm from README

- CONTRIBUTING.md
- package-lock.json
- package.json
- src/program.js
- tests/unit/test.config.js
- tests/unit/test.program.js
This PR updates yargs to version 13.2.1 and also fixes the "Unknown argument: no-config-discovery" issue (#1307).
> fix: Updated yargs to version 13.2.1

- src/cmd/build.js
- tests/fixtures/dashed-locale/_locales/en_US/messages.json
- tests/fixtures/dashed-locale/manifest.json
- tests/unit/test-cmd/test.build.js
> fix: Normalize default_locale before use

- webpack.config.js
See commit message.
Fixes #1629
> fix: Stop bundling dependencies with slashes

- src/program.js
- tests/functional/test.cli.run.js
- tests/unit/test-cmd/test.run.js
> fix: Add supported choices to --target option

- .nsprc
- package-lock.json
> chore: Updated handlebars version in package-lock and cleared nsprc exceptions

- .babelrc
- .travis.yml
- README.md
- package.json
> chore: Upgrade to node 10

- src/extension-runners/chromium.js
- tests/unit/test-extension-runners/test.chromium.js
> fix: make wssBroadcast an async function

- README.md
I fixed broken links in README.md
> docs: Fix broken links to web-ext documentation

- src/config.js
- src/program.js
- tests/functional/test.cli.sign.js
> fix: Validate required parameters after reading config files.

- scripts/lib/mocha.js
> test: Set custom mocha timeout from MOCHA_TIMEOUT environment variable

- README.md
> fix: Wrong example of requiring web-ext

- .travis.yml
- tests/functional/test.cli.run.js
> chore: add nodejs 14 to travis CI matrix and fix functional test failure

- .circleci/config.yml
> chore(ci): Increased functional tests mocha timeout in test-windows job

- CONTRIBUTING.md
- src/program.js
- tests/functional/test.cli.sign.js
- tests/unit/test-cmd/test.sign.js
> fix: Replace AMO API v3 with v4

- src/cmd/build.js
- tests/fixtures/slashed-name/manifest.json
- tests/unit/test-cmd/test.build.js
Fixes #2119 (which was a regression by #1900).
> fix: Sanitize manifest property values before interpolation

- src/extension-runners/chromium.js
> fix: Limit reloads to enabled extensions in chrome extension runner

- scripts/audit-deps.js
This PR contains some small changes to make sure the scripts/audit-deps.js script will parse both the old and new npm audit json format (See #2470 issue comment for a sample of the new and old format).
With the changes included in this PR, the output on npm v8 (See STR from #2470 issue description) will be the following:
```
== audit-deps: blocking security issues
terser (isDirect: true, severity: high, fixAvailable: true):
https://github.com/advisories/GHSA-4wf5-vphf-c2xc
terser >=5.0.0 <5.14.2
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS
```
while on npm v7
```
== audit-deps: blocking security issues
terser (https://github.com/advisories/GHSA-4wf5-vphf-c2xc):
5.14.1 - paths: terser
```
The details in each formatted entry is slightly different, but …
> chore: Fix audit-deps script on the new npm audit format introduced in npm v8

- package-lock.json
- package.json
- src/extension-runners/firefox-desktop.js
- src/firefox/index.js
- src/program.js
- tests/unit/test-firefox/test.firefox.js
Fixes #2465
---
~~This patch isn't enough because the [fx-runner](https://github.com/mozilla/node-fx-runner/) does weird things with the command parameters. With some small changes,~~ things work fine, though:
> feat: allow run command to use flatpak

- .github/dependabot.yml
- renovate.json
Fixes https://github.com/mozilla/web-ext/issues/2588
> chore: use Dependabot instead of Renovate

- src/cmd/sign.js
- src/program.js
- src/util/submit-addon.js
- tests/unit/test-cmd/test.sign.js
- tests/unit/test-util/test.submit-addon.js
- tests/unit/test.program.js
> feat: send UserAgentHeader with signing requests

- README.md
> Update reference to Contact Us page

- .nsprc
> chore(deps): ignore https://github.com/advisories/GHSA-p8p7-x288-28g6 for now

- scripts/audit-deps.js
While reviewing the CI jobs failure hit by most of the dependabot PR opened over the last week we noticed that it was hitting the `audit-deps` step of the CI job but the output of our `audit-deps` npm script (which parses the json output of the `npm audit` command) wasn't always providing the details about the security advisory associated to the reported npm dependency, e.g. like here for nyc: https://app.circleci.com/pipelines/github/mozilla/web-ext/2388/workflows/f22e2ff0-ed9c-4373-88d5-bccb0bf6869c/jobs/9630?invite=true#step-116-141
Looked into the reasons behind that, I noticed that the `audit-deps` script was currently assuming that the via attribute in each of the reported npm packages details was going to be either an object with the details for the security advisory or a string …
> chore: fix audit-deps npm script on deeply nested inherited advisories

- README.md
Fixes https://github.com/mozilla/web-ext/issues/3148
> fix: Fix link to EW in README file

- README.md
> docs: updated links to extension workshop

- README.md
Added `web-ext` to Homebrew here https://github.com/Homebrew/homebrew-core/pull/142942
> Add installation with Homebrew section in README

- package-lock.json
> fix(deps): Bump braces version
